### ISSUE TITLE
dev-util/rizin-0.8.1 and dev-util/cutter-2.4.1 version bump

### ISSUE THREAD

**Issue by notxvilka** [haikuports/haikuports#12365]
A result of a year of work, Rizin 0.8.1:
- https://github.com/rizinorg/rizin/releases/tag/v0.8.0
- https://github.com/rizinorg/rizin/releases/tag/v0.8.1

And corresponding Cutter release:
- https://github.com/rizinorg/cutter/releases/tag/v2.4.0
- https://github.com/rizinorg/cutter/releases/tag/v2.4.1

**Comment by Begasus** [comment]
Unfortunatly getting a linker error at the end of the build for rz_core :/

```
[1654/1667] cc  -o librz/core/librz_core.so.0.8.1 librz/core/librz_core.so.0.8.1.p/meson-generated_.._cmd_descs_cmd_descs.c.o librz/core/librz_core.so.0.8.1.p/agraph.c.o librz/core/librz_core.so.0.8.1.p/analysis_objc.c.o librz/core/librz_core.so.0.8.1.p/analysis_tp.c.o librz/core/librz_core.so.0.8.1.p/basefind.c.o librz/core/librz_core.so.0.8.1.p/cagraph.c.o librz/core/librz_core.so.0.8.1.p/cgraph.c.o librz/core/librz_core.so.0.8.1.p/canalysis.c.o librz/core/librz_core.so.0.8.1.p/cannotated_code.c.o librz/core/librz_core.so.0.8.1.p/carg.c.o librz/core/librz_core.so.0.8.1.p/casm.c.o librz/core/librz_core.so.0.8.1.p/cautocmpl.c.o librz/core/librz_core.so.0.8.1.p/cbin.c.o librz/core/librz_core.so.0.8.1.p/cbounds.c.o librz/core/librz_core.so.0.8.1.p/cconfig.c.o librz/core/librz_core.so.0.8.1.p/ccrypto.c.o librz/core/librz_core.so.0.8.1.p/cdebug.c.o librz/core/librz_core.so.0.8.1.p/cesil.c.o librz/core/librz_core.so.0.8.1.p/cfile.c.o librz/core/librz_core.so.0.8.1.p/cflag.c.o librz/core/librz_core.so.0.8.1.p/chash.c.o librz/core/librz_core.so.0.8.1.p/cheap.c.o librz/core/librz_core.so.0.8.1.p/cil.c.o librz/core/librz_core.so.0.8.1.p/cio.c.o librz/core/librz_core.so.0.8.1.p/clang.c.o librz/core/librz_core.so.0.8.1.p/cmeta.c.o librz/core/librz_core.so.0.8.1.p/cmp.c.o librz/core/librz_core.so.0.8.1.p/core.c.o librz/core/librz_core.so.0.8.1.p/cparser.c.o librz/core/librz_core.so.0.8.1.p/cpdb.c.o librz/core/librz_core.so.0.8.1.p/cplugin.c.o librz/core/librz_core.so.0.8.1.p/cprint.c.o librz/core/librz_core.so.0.8.1.p/creg.c.o librz/core/librz_core.so.0.8.1.p/csearch.c.o librz/core/librz_core.so.0.8.1.p/csign.c.o librz/core/librz_core.so.0.8.1.p/ctypes.c.o librz/core/librz_core.so.0.8.1.p/cvfile.c.o librz/core/librz_core.so.0.8.1.p/csyscall.c.o librz/core/librz_core.so.0.8.1.p/disasm.c.o librz/core/librz_core.so.0.8.1.p/fortune.c.o librz/core/librz_core.so.0.8.1.p/golang.c.o librz/core/librz_core.so.0.8.1.p/hack.c.o librz/core/librz_core.so.0.8.1.p/libs.c.o librz/core/librz_core.so.0.8.1.p/linux_heap_glibc.c.o librz/core/librz_core.so.0.8.1.p/linux_heap_glibc64.c.o librz/core/librz_core.so.0.8.1.p/rop.c.o librz/core/librz_core.so.0.8.1.p/project.c.o librz/core/librz_core.so.0.8.1.p/project_migrate.c.o librz/core/librz_core.so.0.8.1.p/rtr.c.o librz/core/librz_core.so.0.8.1.p/seek.c.o librz/core/librz_core.so.0.8.1.p/serialize_core.c.o librz/core/librz_core.so.0.8.1.p/task.c.o librz/core/librz_core.so.0.8.1.p/yank.c.o librz/core/librz_core.so.0.8.1.p/p_core_dex.c.o librz/core/librz_core.so.0.8.1.p/p_core_java.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_alias.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_api.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_block.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_cmp.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_egg.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_eval.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_flag.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_flirt.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_hash.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_history.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_info.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_interactive.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_interactive_panel.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_interpret.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_macro.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_meta.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_open.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_plugins.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_project.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_query.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_quit.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_remote.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_resize.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_seek.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_shell.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_system.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_tasks.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_type.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_write.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_yank.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_regs.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_linux_heap_glibc.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_windows_heap.c.o librz/core/librz_core.so.0.8.1.p/tui_biteditor.c.o librz/core/librz_core.so.0.8.1.p/tui_classes.c.o librz/core/librz_core.so.0.8.1.p/tui_colors.c.o librz/core/librz_core.so.0.8.1.p/tui_comments.c.o librz/core/librz_core.so.0.8.1.p/tui_config.c.o librz/core/librz_core.so.0.8.1.p/tui_define.c.o librz/core/librz_core.so.0.8.1.p/tui_esil.c.o librz/core/librz_core.so.0.8.1.p/tui_flags.c.o librz/core/librz_core.so.0.8.1.p/tui_hud.c.o librz/core/librz_core.so.0.8.1.p/tui_modes.c.o librz/core/librz_core.so.0.8.1.p/tui_visual.c.o librz/core/librz_core.so.0.8.1.p/tui_vmenus.c.o librz/core/librz_core.so.0.8.1.p/tui_vmenus_graph.c.o librz/core/librz_core.so.0.8.1.p/tui_vasm.c.o librz/core/librz_core.so.0.8.1.p/tui_vmarks.c.o librz/core/librz_core.so.0.8.1.p/tui_panels.c.o librz/core/librz_core.so.0.8.1.p/tui_tabs.c.o librz/core/librz_core.so.0.8.1.p/tui_rop.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,-soname,librz_core.so.0.8 '-Wl,-rpath,$ORIGIN/../util:$ORIGIN/../demangler:$ORIGIN/../diff:$ORIGIN/../magic:$ORIGIN/../socket:$ORIGIN/../flag:$ORIGIN/../cons:$ORIGIN/../lang:$ORIGIN/../hash:$ORIGIN/../crypto:$ORIGIN/../io:$ORIGIN/../reg:$ORIGIN/../bp:$ORIGIN/../syscall:$ORIGIN/../egg:$ORIGIN/../arch:$ORIGIN/../search:$ORIGIN/../config:$ORIGIN/../bin:$ORIGIN/../type:$ORIGIN/../il:$ORIGIN/../sign:$ORIGIN/../debug:/packages/tree_sitter-0.20.10~git-1/.self/develop/lib:/packages/libpcre2-10.45-1/.self/develop/lib:/packages/zlib-1.3.1-4/.self/develop/lib:/packages/xz_utils-5.6.2-2/.self/develop/lib:/packages/openssl3-3.5.0-2/.self/develop/lib:/packages/file-5.43-2/.self/develop/lib:/packages/xxhash-0.8.3-1/.self/develop/lib:/packages/libzip-1.9.2-2/.self/develop/lib:/packages/capstone5-5.0.1-2/.self/develop/lib:/packages/zstd-1.5.6-2/.self/develop/lib:/packages/libmspack-0.10.1~alpha-2/.self/develop/lib' -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/util -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/demangler -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/diff -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/magic -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/socket -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/flag -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/cons -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/lang -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/hash -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/crypto -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/io -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/reg -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/bp -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/syscall -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/egg -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/arch -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/search -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/config -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/bin -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/type -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/il -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/sign -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/debug '-Wl,-rpath-link,/packages/tree_sitter-0.20.10~git-1/.self/develop/lib' -Wl,-rpath-link,/packages/libpcre2-10.45-1/.self/develop/lib -Wl,-rpath-link,/packages/zlib-1.3.1-4/.self/develop/lib -Wl,-rpath-link,/packages/xz_utils-5.6.2-2/.self/develop/lib -Wl,-rpath-link,/packages/openssl3-3.5.0-2/.self/develop/lib -Wl,-rpath-link,/packages/file-5.43-2/.self/develop/lib -Wl,-rpath-link,/packages/xxhash-0.8.3-1/.self/develop/lib -Wl,-rpath-link,/packages/libzip-1.9.2-2/.self/develop/lib -Wl,-rpath-link,/packages/capstone5-5.0.1-2/.self/develop/lib -Wl,-rpath-link,/packages/zstd-1.5.6-2/.self/develop/lib '-Wl,-rpath-link,/packages/libmspack-0.10.1~alpha-2/.self/develop/lib' -Wl,--start-group librz/util/librz_util.so.0.8.1 librz/demangler/librz_demangler.so.0.8.1 librz/diff/librz_diff.so.0.8.1 librz/magic/librz_magic.so.0.8.1 librz/socket/librz_socket.so.0.8.1 librz/flag/librz_flag.so.0.8.1 librz/cons/librz_cons.so.0.8.1 librz/lang/librz_lang.so.0.8.1 librz/hash/librz_hash.so.0.8.1 librz/crypto/librz_crypto.so.0.8.1 librz/io/librz_io.so.0.8.1 librz/reg/librz_reg.so.0.8.1 librz/bp/librz_bp.so.0.8.1 librz/syscall/librz_syscall.so.0.8.1 librz/egg/librz_egg.so.0.8.1 librz/search/librz_search.so.0.8.1 librz/sign/librz_sign.so.0.8.1 librz/il/librz_il.so.0.8.1 librz/arch/librz_arch.so.0.8.1 librz/type/librz_type.so.0.8.1 librz/debug/librz_debug.so.0.8.1 librz/config/librz_config.so.0.8.1 librz/bin/librz_bin.so.0.8.1 subprojects/rzgdb/librzgdb.a subprojects/rizin-shell-parser/libshell_parser.a '/packages/tree_sitter-0.20.10~git-1/.self/develop/lib/libtree-sitter.so' -lm -Wl,--end-group
FAILED: librz/core/librz_core.so.0.8.1 
cc  -o librz/core/librz_core.so.0.8.1 librz/core/librz_core.so.0.8.1.p/meson-generated_.._cmd_descs_cmd_descs.c.o librz/core/librz_core.so.0.8.1.p/agraph.c.o librz/core/librz_core.so.0.8.1.p/analysis_objc.c.o librz/core/librz_core.so.0.8.1.p/analysis_tp.c.o librz/core/librz_core.so.0.8.1.p/basefind.c.o librz/core/librz_core.so.0.8.1.p/cagraph.c.o librz/core/librz_core.so.0.8.1.p/cgraph.c.o librz/core/librz_core.so.0.8.1.p/canalysis.c.o librz/core/librz_core.so.0.8.1.p/cannotated_code.c.o librz/core/librz_core.so.0.8.1.p/carg.c.o librz/core/librz_core.so.0.8.1.p/casm.c.o librz/core/librz_core.so.0.8.1.p/cautocmpl.c.o librz/core/librz_core.so.0.8.1.p/cbin.c.o librz/core/librz_core.so.0.8.1.p/cbounds.c.o librz/core/librz_core.so.0.8.1.p/cconfig.c.o librz/core/librz_core.so.0.8.1.p/ccrypto.c.o librz/core/librz_core.so.0.8.1.p/cdebug.c.o librz/core/librz_core.so.0.8.1.p/cesil.c.o librz/core/librz_core.so.0.8.1.p/cfile.c.o librz/core/librz_core.so.0.8.1.p/cflag.c.o librz/core/librz_core.so.0.8.1.p/chash.c.o librz/core/librz_core.so.0.8.1.p/cheap.c.o librz/core/librz_core.so.0.8.1.p/cil.c.o librz/core/librz_core.so.0.8.1.p/cio.c.o librz/core/librz_core.so.0.8.1.p/clang.c.o librz/core/librz_core.so.0.8.1.p/cmeta.c.o librz/core/librz_core.so.0.8.1.p/cmp.c.o librz/core/librz_core.so.0.8.1.p/core.c.o librz/core/librz_core.so.0.8.1.p/cparser.c.o librz/core/librz_core.so.0.8.1.p/cpdb.c.o librz/core/librz_core.so.0.8.1.p/cplugin.c.o librz/core/librz_core.so.0.8.1.p/cprint.c.o librz/core/librz_core.so.0.8.1.p/creg.c.o librz/core/librz_core.so.0.8.1.p/csearch.c.o librz/core/librz_core.so.0.8.1.p/csign.c.o librz/core/librz_core.so.0.8.1.p/ctypes.c.o librz/core/librz_core.so.0.8.1.p/cvfile.c.o librz/core/librz_core.so.0.8.1.p/csyscall.c.o librz/core/librz_core.so.0.8.1.p/disasm.c.o librz/core/librz_core.so.0.8.1.p/fortune.c.o librz/core/librz_core.so.0.8.1.p/golang.c.o librz/core/librz_core.so.0.8.1.p/hack.c.o librz/core/librz_core.so.0.8.1.p/libs.c.o librz/core/librz_core.so.0.8.1.p/linux_heap_glibc.c.o librz/core/librz_core.so.0.8.1.p/linux_heap_glibc64.c.o librz/core/librz_core.so.0.8.1.p/rop.c.o librz/core/librz_core.so.0.8.1.p/project.c.o librz/core/librz_core.so.0.8.1.p/project_migrate.c.o librz/core/librz_core.so.0.8.1.p/rtr.c.o librz/core/librz_core.so.0.8.1.p/seek.c.o librz/core/librz_core.so.0.8.1.p/serialize_core.c.o librz/core/librz_core.so.0.8.1.p/task.c.o librz/core/librz_core.so.0.8.1.p/yank.c.o librz/core/librz_core.so.0.8.1.p/p_core_dex.c.o librz/core/librz_core.so.0.8.1.p/p_core_java.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_alias.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_api.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_block.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_cmp.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_egg.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_eval.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_flag.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_flirt.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_hash.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_history.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_info.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_interactive.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_interactive_panel.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_interpret.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_macro.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_meta.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_open.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_plugins.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_project.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_query.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_quit.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_remote.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_resize.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_seek.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_shell.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_system.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_tasks.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_type.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_write.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_yank.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_regs.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_linux_heap_glibc.c.o librz/core/librz_core.so.0.8.1.p/cmd_cmd_windows_heap.c.o librz/core/librz_core.so.0.8.1.p/tui_biteditor.c.o librz/core/librz_core.so.0.8.1.p/tui_classes.c.o librz/core/librz_core.so.0.8.1.p/tui_colors.c.o librz/core/librz_core.so.0.8.1.p/tui_comments.c.o librz/core/librz_core.so.0.8.1.p/tui_config.c.o librz/core/librz_core.so.0.8.1.p/tui_define.c.o librz/core/librz_core.so.0.8.1.p/tui_esil.c.o librz/core/librz_core.so.0.8.1.p/tui_flags.c.o librz/core/librz_core.so.0.8.1.p/tui_hud.c.o librz/core/librz_core.so.0.8.1.p/tui_modes.c.o librz/core/librz_core.so.0.8.1.p/tui_visual.c.o librz/core/librz_core.so.0.8.1.p/tui_vmenus.c.o librz/core/librz_core.so.0.8.1.p/tui_vmenus_graph.c.o librz/core/librz_core.so.0.8.1.p/tui_vasm.c.o librz/core/librz_core.so.0.8.1.p/tui_vmarks.c.o librz/core/librz_core.so.0.8.1.p/tui_panels.c.o librz/core/librz_core.so.0.8.1.p/tui_tabs.c.o librz/core/librz_core.so.0.8.1.p/tui_rop.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,-soname,librz_core.so.0.8 '-Wl,-rpath,$ORIGIN/../util:$ORIGIN/../demangler:$ORIGIN/../diff:$ORIGIN/../magic:$ORIGIN/../socket:$ORIGIN/../flag:$ORIGIN/../cons:$ORIGIN/../lang:$ORIGIN/../hash:$ORIGIN/../crypto:$ORIGIN/../io:$ORIGIN/../reg:$ORIGIN/../bp:$ORIGIN/../syscall:$ORIGIN/../egg:$ORIGIN/../arch:$ORIGIN/../search:$ORIGIN/../config:$ORIGIN/../bin:$ORIGIN/../type:$ORIGIN/../il:$ORIGIN/../sign:$ORIGIN/../debug:/packages/tree_sitter-0.20.10~git-1/.self/develop/lib:/packages/libpcre2-10.45-1/.self/develop/lib:/packages/zlib-1.3.1-4/.self/develop/lib:/packages/xz_utils-5.6.2-2/.self/develop/lib:/packages/openssl3-3.5.0-2/.self/develop/lib:/packages/file-5.43-2/.self/develop/lib:/packages/xxhash-0.8.3-1/.self/develop/lib:/packages/libzip-1.9.2-2/.self/develop/lib:/packages/capstone5-5.0.1-2/.self/develop/lib:/packages/zstd-1.5.6-2/.self/develop/lib:/packages/libmspack-0.10.1~alpha-2/.self/develop/lib' -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/util -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/demangler -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/diff -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/magic -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/socket -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/flag -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/cons -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/lang -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/hash -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/crypto -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/io -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/reg -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/bp -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/syscall -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/egg -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/arch -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/search -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/config -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/bin -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/type -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/il -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/sign -Wl,-rpath-link,/sources/rizin-0.8.1/build/librz/debug '-Wl,-rpath-link,/packages/tree_sitter-0.20.10~git-1/.self/develop/lib' -Wl,-rpath-link,/packages/libpcre2-10.45-1/.self/develop/lib -Wl,-rpath-link,/packages/zlib-1.3.1-4/.self/develop/lib -Wl,-rpath-link,/packages/xz_utils-5.6.2-2/.self/develop/lib -Wl,-rpath-link,/packages/openssl3-3.5.0-2/.self/develop/lib -Wl,-rpath-link,/packages/file-5.43-2/.self/develop/lib -Wl,-rpath-link,/packages/xxhash-0.8.3-1/.self/develop/lib -Wl,-rpath-link,/packages/libzip-1.9.2-2/.self/develop/lib -Wl,-rpath-link,/packages/capstone5-5.0.1-2/.self/develop/lib -Wl,-rpath-link,/packages/zstd-1.5.6-2/.self/develop/lib '-Wl,-rpath-link,/packages/libmspack-0.10.1~alpha-2/.self/develop/lib' -Wl,--start-group librz/util/librz_util.so.0.8.1 librz/demangler/librz_demangler.so.0.8.1 librz/diff/librz_diff.so.0.8.1 librz/magic/librz_magic.so.0.8.1 librz/socket/librz_socket.so.0.8.1 librz/flag/librz_flag.so.0.8.1 librz/cons/librz_cons.so.0.8.1 librz/lang/librz_lang.so.0.8.1 librz/hash/librz_hash.so.0.8.1 librz/crypto/librz_crypto.so.0.8.1 librz/io/librz_io.so.0.8.1 librz/reg/librz_reg.so.0.8.1 librz/bp/librz_bp.so.0.8.1 librz/syscall/librz_syscall.so.0.8.1 librz/egg/librz_egg.so.0.8.1 librz/search/librz_search.so.0.8.1 librz/sign/librz_sign.so.0.8.1 librz/il/librz_il.so.0.8.1 librz/arch/librz_arch.so.0.8.1 librz/type/librz_type.so.0.8.1 librz/debug/librz_debug.so.0.8.1 librz/config/librz_config.so.0.8.1 librz/bin/librz_bin.so.0.8.1 subprojects/rzgdb/librzgdb.a subprojects/rizin-shell-parser/libshell_parser.a '/packages/tree_sitter-0.20.10~git-1/.self/develop/lib/libtree-sitter.so' -lm -Wl,--end-group
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: librz/core/librz_core.so.0.8.1.p/linux_heap_glibc.c.o: in function `resolve_heap_tcache_32':
linux_heap_glibc.c:(.text+0x609f): undefined reference to `rz_debug_get_tls'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: linux_heap_glibc.c:(.text+0x60e8): undefined reference to `rz_debug_native_threads'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: librz/core/librz_core.so.0.8.1.p/linux_heap_glibc64.c.o: in function `resolve_heap_tcache_64':
linux_heap_glibc64.c:(.text+0x60f0): undefined reference to `rz_debug_get_tls'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: linux_heap_glibc64.c:(.text+0x6138): undefined reference to `rz_debug_native_threads'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 1.
cleaning 'chroot/boot' folder
keeping chroot folder /Opslag/haikuports/dev-util/rizin/work-0.8.1 intact for inspection
Error: Build has failed - stopping.
```

**Comment by Begasus** [comment]
Probably related to: https://github.com/rizinorg/rizin/pull/4615

**Comment by notxvilka** [comment]
@well-mannered-goat could you please take a look at this, since it's directly related to the debugger task?

**Comment by well-mannered-goat** [comment]
It seems that the files `linux_heap_glibc64.c` `linux_heap_glibc.c` call the functions `rz_debug_get_tls` and `rz_debug_native_threads`. But we dont compile these functions for HAIKU in any native architecture debugger. Should I ignore these calls for haiku ?? Just want to make sure I am headed in the right direction.

**Comment by notxvilka** [comment]
> It seems that the files `linux_heap_glibc64.c` `linux_heap_glibc.c` call the functions `rz_debug_get_tls` and `rz_debug_native_threads`. But we dont compile these functions for HAIKU in any native architecture debugger. Should I ignore these calls for haiku ?? Just want to make sure I am headed in the right direction.

Yes, at least until we support Haiku OS-specific threads and TLS handling

**Comment by Begasus** [comment]
I thought in that direction, but my skills ... :) Thanks for looking into this, if there is a "fix" I can check just keep me posted. :)

**Comment by wargio** [comment]
I just checked the code. this is missing a file for haiku OS, let me see if i can just add this.

**Comment by wargio** [comment]
Please try the patch https://github.com/rizinorg/rizin/pull/5149.patch

**Comment by Begasus** [comment]
> Please try the patch https://github.com/rizinorg/rizin/pull/5149.patch
> 
> I have built rizin (dev) successfully after these changes. if they work for you too, we can backport and release a new version with just this patch

Build went fine with the patch, also Cutter 2.4.1 build was ok with it (no need to patch for rizen detection, that's a big plus!), but unfortunatly Cutter crashes on launch. :/

Not much from Terminal launch:

```
~> Cutter
qt.qpa.openglcontext: Created 0x10eaff052fe0 based on requested QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior::DoubleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::OpenGLContextProfile::NoProfile)
"0.8.1" "0.8.1"
Kill Thread
```

**Comment by wargio** [comment]
can you provide a crash dump?

**Comment by Begasus** [comment]
> can you provide a crash dump? did you also make a clean build?

I can provide a crash report, not sure how to grab a crash dump?

[Cutter-108982-debug-17-05-2025-13-32-55.report.txt](https://github.com/user-attachments/files/20265066/Cutter-108982-debug-17-05-2025-13-32-55.report.txt)

**Comment by wargio** [comment]
maybe it's a null pointer.
can you try to open the same file with rizin?

**Comment by Begasus** [comment]
> can you try to open the same file with rizin

How do you mean, Cutter is build against rizin, so I don't see how?

Thanks in advance, might want to add that I'm running an experimental(*so far seems pretty stable) Qt version (default in Haiku depot is still Qt6.7.2).

**Comment by wargio** [comment]
> > can you try to open the same file with rizin
> 
> How do you mean, Cutter is build against rizin, so I don't see how?
> 
> Thanks in advance, might want to add that I'm running an experimental(*so far seems pretty stable) Qt version (default in Haiku depot is still Qt6.7.2).

I guess from the reply that you just opened it

**Comment by Begasus** [comment]
> I guess from the reply that you just opened it without select any file

Right, launching from Terminal without a selected file:

```
~> Cutter 
qt.qpa.openglcontext: Created 0x10bbc54f1020 based on requested QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior::DoubleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::OpenGLContextProfile::NoProfile)
"0.8.1" "0.8.1"
Kill Thread
```

The same if I seletc a file like `Cutter filename /bin/cp`

**Comment by pulkomandy** [comment]
The crash happens in tree_sitter. We are using a very old version of it that isn't even an official release.

I tried to update it but newer versions fail to build due to a problem in Rustix.

So I fixed that here: https://github.com/bytecodealliance/rustix/pull/1493

Once it is merged we have to figure out how to get it included in the tree-sitter build, update tree-sitter, and see if that helps.

**Comment by Begasus** [comment]
Did a build from latest commit on tree-sitter which doesn't use the old rustix (that came with fs4) anymore, full rebuild for rizen and cutter still crashes:

```
~> gdb Cutter 
GNU gdb (GDB) 15.1
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-haiku".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from Cutter...
(No debugging symbols found in Cutter)
(gdb) run
Starting program: /boot/system/apps/Cutter 
[New team 52397 (Cutter) thread 52402 (BApplication_thread)]
"0.8.1" "0.8.1"
[Detaching after fork from child team 52403 (Cutter)]
[Detaching after fork from child team 52404 (Cutter)]
WARNING: rz_debug_plugin_add: assertion 'dbg && plugin && plugin->name' failed (line 54)
Plugins are loaded from "/boot/system/cache/rizin/cutter/plugins"
Native plugins are loaded from "/boot/system/cache/rizin/cutter/plugins/native"
Loaded 0 plugin(s).
Plugins are loaded from "/boot/home/config/non-packaged/data/rizin/cutter/plugins"
Plugins are loaded from "/boot/home/config/data/rizin/cutter/plugins"
Plugins are loaded from "/boot/system/non-packaged/data/rizin/cutter/plugins"
Plugins are loaded from "/boot/system/data/rizin/cutter/plugins"
[New team 52397 (Cutter) thread 52406 (w>)]
[New team 52397 (Cutter) thread 52454 (w>)]
[team 52397 (Cutter) thread 52406 exited]
[New team 52397 (Cutter) thread 52460 (pthread func)]
[New team 52397 (Cutter) thread 52461 (pthread func)]
[New team 52397 (Cutter) thread 52462 (pthread func)]
[New team 52397 (Cutter) thread 52463 (pthread func)]
[New team 52397 (Cutter) thread 52464 (pthread func)]
[New team 52397 (Cutter) thread 52472 (pthread func)]
[New team 52397 (Cutter) thread 52479 (pthread func)]
[New team 52397 (Cutter) thread 52493 (w>)]
[New team 52397 (Cutter) thread 52494 (pthread func)]
[team 52397 (Cutter) thread 52454 exited]
[New team 52397 (Cutter) thread 52495 (pthread func)]
[New team 52397 (Cutter) thread 52496 (pthread func)]
[team 52397 (Cutter) thread 52496 exited]
[New team 52397 (Cutter) thread 52498 (pthread func)]
[team 52397 (Cutter) thread 52498 exited]
[New team 52397 (Cutter) thread 52500 (pthread func)]
[New team 52397 (Cutter) thread 52501 (pthread func)]
[team 52397 (Cutter) thread 52500 exited]
[team 52397 (Cutter) thread 52501 exited]
[team 52397 (Cutter) thread 52495 exited]
[New team 52397 (Cutter) thread 52502 (pthread func)]
[team 52397 (Cutter) thread 52502 exited]
[New team 52397 (Cutter) thread 52503 (pthread func)]
[team 52397 (Cutter) thread 52503 exited]
[New team 52397 (Cutter) thread 52504 (pthread func)]
[team 52397 (Cutter) thread 52504 exited]
[New team 52397 (Cutter) thread 52505 (pthread func)]
[team 52397 (Cutter) thread 52505 exited]
[New team 52397 (Cutter) thread 52507 (pthread func)]
[team 52397 (Cutter) thread 52507 exited]
[New team 52397 (Cutter) thread 52508 (pthread func)]
[team 52397 (Cutter) thread 52508 exited]
[New team 52397 (Cutter) thread 52509 (pthread func)]
[team 52397 (Cutter) thread 52509 exited]
[New team 52397 (Cutter) thread 52510 (pthread func)]
[team 52397 (Cutter) thread 52510 exited]
[New team 52397 (Cutter) thread 52511 (pthread func)]
[team 52397 (Cutter) thread 52511 exited]
[New team 52397 (Cutter) thread 52513 (pthread func)]
[team 52397 (Cutter) thread 52513 exited]
[New team 52397 (Cutter) thread 52514 (pthread func)]
[team 52397 (Cutter) thread 52514 exited]
ERROR: Cannot determine entrypoint, using 0x00003260.
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls
[x] Analyze len bytes of instructions for references
[x] Check for classes
[x] Analyze local variables and arguments
[x] Type matching analysis for all functions
[x] Applied 0 FLIRT signatures via sigdb
[x] Propagate noreturn information
[x] Integrate dwarf function information.
[x] Resolve pointers to data sections
[x] Use -AA or aaaa to perform additional experimental analysis.
[New team 52397 (Cutter) thread 52572 (pthread func)]
[New team 52397 (Cutter) thread 52573 (pthread func)]
[New team 52397 (Cutter) thread 52574 (pthread func)]
[New team 52397 (Cutter) thread 52575 (pthread func)]
[team 52397 (Cutter) thread 52573 exited]
[team 52397 (Cutter) thread 52575 exited]
[New team 52397 (Cutter) thread 52576 (pthread func)]
[team 52397 (Cutter) thread 52576 exited]
[New team 52397 (Cutter) thread 52577 (pthread func)]
[team 52397 (Cutter) thread 52577 exited]
[New team 52397 (Cutter) thread 52578 (pthread func)]
[team 52397 (Cutter) thread 52572 exited]
[team 52397 (Cutter) thread 52578 exited]
[team 52397 (Cutter) thread 52574 exited]
[New team 52397 (Cutter) thread 52579 (pthread func)]
[team 52397 (Cutter) thread 52579 exited]
[New team 52397 (Cutter) thread 52580 (pthread func)]
[team 52397 (Cutter) thread 52580 exited]
[New team 52397 (Cutter) thread 52581 (pthread func)]
[team 52397 (Cutter) thread 52581 exited]
[New team 52397 (Cutter) thread 52582 (pthread func)]
[team 52397 (Cutter) thread 52582 exited]
[New team 52397 (Cutter) thread 52583 (pthread func)]
[team 52397 (Cutter) thread 52583 exited]
[New team 52397 (Cutter) thread 52584 (pthread func)]
[team 52397 (Cutter) thread 52584 exited]
[New team 52397 (Cutter) thread 52585 (pthread func)]
[team 52397 (Cutter) thread 52585 exited]
[New team 52397 (Cutter) thread 52586 (pthread func)]
[team 52397 (Cutter) thread 52586 exited]
[New team 52397 (Cutter) thread 52587 (pthread func)]
[team 52397 (Cutter) thread 52587 exited]
[New team 52397 (Cutter) thread 52589 (w>)]
Thread 52397 caused an exception: Segment violation

Thread 1 "Cutter" received signal SIGSEGV, Segmentation fault.
0x00000000015a1f35 in QWidget::testAttribute_helper(Qt::WidgetAttribute) const () from /boot/system/lib/libQt6Widgets.so.6.10.2
(gdb) backtrace 
#0  0x00000000015a1f35 in QWidget::testAttribute_helper(Qt::WidgetAttribute) const () from /boot/system/lib/libQt6Widgets.so.6.10.2
#1  0x00000000015afddf in QWidget::setAttribute(Qt::WidgetAttribute, bool) () from /boot/system/lib/libQt6Widgets.so.6.10.2
#2  0x00000000015be1b7 in QWidgetPrivate::setVisible(bool) () from /boot/system/lib/libQt6Widgets.so.6.10.2
#3  0x000000000171cf4d in QMainWindowLayout::showTabBars() () from /boot/system/lib/libQt6Widgets.so.6.10.2
#4  0x00000000017251d4 in QMainWindowLayout::animationFinished(QWidget*) () from /boot/system/lib/libQt6Widgets.so.6.10.2
#5  0x000000000171f237 in QMainWindowLayout::takeAt(int) () from /boot/system/lib/libQt6Widgets.so.6.10.2
#6  0x000000000158f5d0 in removeWidgetRecursively(QLayoutItem*, QObject*) () from /boot/system/lib/libQt6Widgets.so.6.10.2
#7  0x000000000158f6d9 in QLayout::addChildWidget(QWidget*) () from /boot/system/lib/libQt6Widgets.so.6.10.2
#8  0x000000000171a9d3 in QMainWindowLayout::tabifyDockWidget(QDockWidget*, QDockWidget*) () from /boot/system/lib/libQt6Widgets.so.6.10.2
#9  0x00000000007a0810 in MainWindow::restoreDocks() ()
#10 0x00000000007a48e8 in MainWindow::setViewLayout(Cutter::CutterLayout const&) ()
#11 0x00000000007a943e in MainWindow::finalizeOpen() ()
#12 0x0000000002775086 in QObject::event(QEvent*) () from /boot/system/lib/libQt6Core.so.6.10.2
#13 0x0000000001557d0d in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /boot/system/lib/libQt6Widgets.so.6.10.2
#14 0x000000000271bff0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /boot/system/lib/libQt6Core.so.6.10.2
#15 0x000000000272038f in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /boot/system/lib/libQt6Core.so.6.10.2
#16 0x00000000028eff4a in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /boot/system/lib/libQt6Core.so.6.10.2
#17 0x0000000002378192 in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /boot/system/lib/libQt6Gui.so.6.10.2
#18 0x0000000002728b9b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /boot/system/lib/libQt6Core.so.6.10.2
#19 0x0000000002724475 in QCoreApplication::exec() () from /boot/system/lib/libQt6Core.so.6.10.2
#20 0x00000000006db941 in main ()
(gdb) continue 
Continuing.

Thread 1 "Cutter" received signal SIGSEGV, Segmentation fault.
0x00000000015a1f35 in QWidget::testAttribute_helper(Qt::WidgetAttribute) const () from /boot/system/lib/libQt6Widgets.so.6.10.2
(gdb) continue 
Continuing.
haiku_nat_target::resume: Bad port ID.
(gdb) 
Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.

The program is not being run.
(gdb) quit
~> 
```
Not sure if it's my experimental Qt version here :)

**Comment by Begasus** [comment]
And now it launched! :D 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/cd4b9a01-7da9-4a2d-866e-3db838b5f83c" />

**Comment by Begasus** [comment]
Things are fixed by now, tree-sitter issue was also resolved, closing.
