### ISSUE TITLE
Upstream Ruby patches

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#1329]

**Comment by miqlas** [comment]
Upstreaming the 2.2.x patches makes no sense, as the 2.2.x branch is already in "security maintenance phase".

The 2.4.x version doesn't need too big patches to get compiled, but the file locking patch isn't too nice, it should be fixed somehow:
https://github.com/haikuports/haikuports/pull/700/files#diff-5cfdaae8d16f64bc0b83bbad35bd8f0bR1

We should port the 2.3.x or the 2.4.x versions.

**Comment by extrowerk** [comment]
2.5 dont need any existing Patch from the earlier versions, but the file locking Problem is still there.
