### ISSUE TITLE
libpurple build failures

### ISSUE THREAD

**Issue by Lan72** [haikuports/haikuports#2332]
Attempts to build libpurple_x86 fail.
What are these problems with NSS SSL development headers?
file:///boot/home/Desktop/Errors_in_building_libpurple_x86.txt

**Comment by Lan72** [comment]
~> hp libpurple_x86
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
----------------------------------------------------------------------
dev-libs::libpurple_x86-2.12.0
        /boot/home/haikuports/dev-libs/libpurple/libpurple-2.12.0.recipe
----------------------------------------------------------------------
Skipping download of source for pidgin-2.12.0.tar.bz2
Skipping checksum validation of pidgin-2.12.0.tar.bz2
Skipping unpack of pidgin-2.12.0.tar.bz2
Cleaning up temporary directories ...
chroot has these packages active:
        /boot/home/haikuports/packages/binutils_x86-2.26.1_2016_07_22-5-x86_gcc2.hpkg
        /boot/home/haikuports/packages/glib2_x86-2.53.5-2-x86_gcc2.hpkg
        /boot/home/haikuports/packages/glib2_x86_devel-2.53.5-2-x86_gcc2.hpkg
        /boot/home/haikuports/packages/gmp_x86-6.1.2-2-x86_gcc2.hpkg
        /boot/home/haikuports/packages/libpcre_x86-8.41-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/libpcre_x86_devel-8.41-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/libpng16-1.6.34-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/libpng16_x86-1.6.34-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/libxml2_x86-2.9.7-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/libxml2_x86_devel-2.9.7-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/make-4.1-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/ncurses6_x86-6.0-3-x86_gcc2.hpkg
        /boot/home/haikuports/packages/ncurses6_x86_devel-6.0-3-x86_gcc2.hpkg
        /boot/home/haikuports/packages/zlib-1.2.11-2-x86_gcc2.hpkg
        /boot/home/haikuports/packages/zlib_x86-1.2.11-2-x86_gcc2.hpkg
        /boot/home/haikuports/packages/zlib_x86_devel-1.2.11-2-x86_gcc2.hpkg
        /boot/system/packages/autoconf-2.69-8-x86_gcc2.hpkg
        /boot/system/packages/automake-1.15.1-1-x86_gcc2.hpkg
        /boot/system/packages/bash-4.4.012-3-x86_gcc2.hpkg
        /boot/system/packages/binutils-2.17_2016_07_24-4-x86_gcc2.hpkg
        /boot/system/packages/bzip2-1.0.6-6-x86_gcc2.hpkg
        /boot/system/packages/bzip2_x86-1.0.6-6-x86_gcc2.hpkg
        /boot/system/packages/ca_root_certificates-2018_01_17-2-any.hpkg
        /boot/system/packages/coreutils-8.24-1-x86_gcc2.hpkg
        /boot/system/packages/curl-7.58.0-1-x86_gcc2.hpkg
        /boot/system/packages/diffutils-3.5-2-x86_gcc2.hpkg
        /boot/system/packages/expat-2.2.1-2-x86_gcc2.hpkg
        /boot/system/packages/expat_x86-2.2.5-1-x86_gcc2.hpkg
        /boot/system/packages/file-5.32-1-x86_gcc2.hpkg
        /boot/system/packages/file_data-5.32-1-any.hpkg
        /boot/system/packages/findutils-4.6.0-1-x86_gcc2.hpkg
        /boot/system/packages/fontconfig-2.12.6-1-x86_gcc2.hpkg
        /boot/system/packages/freetype-2.9-1-x86_gcc2.hpkg
        /boot/system/packages/freetype_x86-2.9-1-x86_gcc2.hpkg
        /boot/system/packages/gawk-4.1.4-2-x86_gcc2.hpkg
        /boot/system/packages/gcc_x86-5.4.0_2016_06_04-7-x86_gcc2.hpkg
        /boot/system/packages/gcc_x86_syslibs-5.4.0_2016_06_04-7-x86_gcc2.hpkg
        /boot/system/packages/gettext-0.19.8.1-5-x86_gcc2.hpkg
        /boot/system/packages/gettext_libintl-0.19.8.1-5-x86_gcc2.hpkg
        /boot/system/packages/gettext_x86-0.19.8.1-5-x86_gcc2.hpkg
        /boot/system/packages/gettext_x86_libintl-0.19.8.1-5-x86_gcc2.hpkg
        /boot/system/packages/giflib6-5.0.5-4-x86_gcc2.hpkg
        /boot/system/packages/giflib6_x86-5.0.5-4-x86_gcc2.hpkg
        /boot/system/packages/grep-2.24-1-x86_gcc2.hpkg
        /boot/system/packages/gutenprint-5.2.13-2-x86_gcc2.hpkg
        /boot/system/packages/gzip-1.8-2-x86_gcc2.hpkg
        /boot/system/packages/haiku-r1~alpha4_pm_hrev51854-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_devel-r1~alpha4_pm_hrev51854-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_x86-r1~alpha4_pm_hrev51854-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_x86_devel-r1~alpha4_pm_hrev51854-1-x86_gcc2.hpkg
        /boot/system/packages/icu-57.1-2-x86_gcc2.hpkg
        /boot/system/packages/icu_x86-57.1-2-x86_gcc2.hpkg
        /boot/system/packages/ilmbase-2.2.1-1-x86_gcc2.hpkg
        /boot/system/packages/ilmbase_x86-2.2.1-1-x86_gcc2.hpkg
        /boot/system/packages/intltool-0.51.0-4-any.hpkg
        /boot/system/packages/jasper-2.0.14-1-x86_gcc2.hpkg
        /boot/system/packages/jasper1_x86-1.900.5-1-x86_gcc2.hpkg
        /boot/system/packages/jasper_x86-2.0.14-1-x86_gcc2.hpkg
        /boot/system/packages/jpeg-9c-1-x86_gcc2.hpkg
        /boot/system/packages/jpeg_x86-9c-1-x86_gcc2.hpkg
        /boot/system/packages/libffi-3.0.13-2-x86_gcc2.hpkg
        /boot/system/packages/libffi_x86-3.2.1-4-x86_gcc2.hpkg
        /boot/system/packages/libffi_x86_devel-3.2.1-4-x86_gcc2.hpkg
        /boot/system/packages/libicns-0.8.1-6-x86_gcc2.hpkg
        /boot/system/packages/libicns_x86-0.8.1-6-x86_gcc2.hpkg
        /boot/system/packages/libiconv-1.15-4-x86_gcc2.hpkg
        /boot/system/packages/libiconv_x86-1.13.1-9-x86_gcc2.hpkg
        /boot/system/packages/libiconv_x86_devel-1.13.1-9-x86_gcc2.hpkg
        /boot/system/packages/libidn_x86-1.33-2-x86_gcc2.hpkg
        /boot/system/packages/libidn_x86_devel-1.33-2-x86_gcc2.hpkg
        /boot/system/packages/libsolv-0.3.0_haiku_2014_12_22-2-x86_gcc2.hpkg
        /boot/system/packages/libsolv_x86-0.3.0_haiku_2014_12_22-2-x86_gcc2.hpkg
        /boot/system/packages/libtool_x86-2.4.6-1-x86_gcc2.hpkg
        /boot/system/packages/libtool_x86_libltdl-2.4.6-1-x86_gcc2.hpkg
        /boot/system/packages/libwebp-0.6.1-2-x86_gcc2.hpkg
        /boot/system/packages/libwebp_x86-0.6.1-2-x86_gcc2.hpkg
        /boot/system/packages/libxml2-2.9.3-5-x86_gcc2.hpkg
        /boot/system/packages/m4-1.4.18-3-x86_gcc2.hpkg
        /boot/system/packages/mpc_x86-1.1.0-1-x86_gcc2.hpkg
        /boot/system/packages/mpfr_x86-3.1.6-2-x86_gcc2.hpkg
        /boot/system/packages/ncurses6-6.0-3-x86_gcc2.hpkg
        /boot/system/packages/noto-20170920-3-any.hpkg
        /boot/system/packages/noto_sans_cjk_jp-1.004-2-any.hpkg
        /boot/system/packages/nspr_x86-4.12-2-x86_gcc2.hpkg
        /boot/system/packages/nspr_x86_devel-4.12-2-x86_gcc2.hpkg
        /boot/system/packages/nss_x86-3.23-5-x86_gcc2.hpkg
        /boot/system/packages/nss_x86_devel-3.23-5-x86_gcc2.hpkg
        /boot/system/packages/openexr-2.2.1-2-x86_gcc2.hpkg
        /boot/system/packages/openexr_x86-2.2.1-2-x86_gcc2.hpkg
        /boot/system/packages/openssl-1.0.2n-1-x86_gcc2.hpkg
        /boot/system/packages/openssl_x86-1.0.2n-1-x86_gcc2.hpkg
        /boot/system/packages/openssl_x86_devel-1.0.2n-1-x86_gcc2.hpkg
        /boot/system/packages/perl-5.26.1-2-x86_gcc2.hpkg
        /boot/system/packages/pkgconfig_x86-0.29.2-3-x86_gcc2.hpkg
        /boot/system/packages/python-2.7.12-1-x86_gcc2.hpkg
        /boot/system/packages/readline-7.0.3-1-x86_gcc2.hpkg
        /boot/system/packages/readline6-6.3.8-2-x86_gcc2.hpkg
        /boot/system/packages/sed-4.2.1-6-x86_gcc2.hpkg
        /boot/system/packages/sqlite-3.22.0.0-1-x86_gcc2.hpkg
        /boot/system/packages/sqlite_x86-3.22.0.0-1-x86_gcc2.hpkg
        /boot/system/packages/tar-1.29-3-x86_gcc2.hpkg
        /boot/system/packages/tiff4-4.0.9-1-x86_gcc2.hpkg
        /boot/system/packages/tiff4_x86-4.0.9-1-x86_gcc2.hpkg
        /boot/system/packages/unzip-6.10c23-2-x86_gcc2.hpkg
        /boot/system/packages/xml_parser-2.44-7-x86_gcc2.hpkg
----- Package Info ----------------
header size:                     80
heap size:                     1044
TOC size:                        41
package attributes size:       1616
total size:                    1124
-----------------------------------
----- Package Info ----------------
header size:                     80
heap size:                      903
TOC size:                        41
package attributes size:       1191
total size:                     983
-----------------------------------
----- Package Info ----------------
header size:                     80
heap size:                     1020
TOC size:                        41
package attributes size:       1449
total size:                    1100
-----------------------------------
waiting for build package libpurple_x86-2.12.0-1 to be activated
waiting for build package libpurple_x86_devel-2.12.0-1 to be activated
waiting for build package libpurple_x86_finch-2.12.0-1 to be activated
Building ...
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:111: installing './compile'
configure.ac:77: installing './missing'
finch/Makefile.am: installing './depcomp'
libpurple/Makefile.am:34: warning: source file 'media/backend-fs2.c' is in a subdirectory,
libpurple/Makefile.am:34: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
libpurple/Makefile.am:34: warning: source file 'media/backend-iface.c' is in a subdirectory,
libpurple/Makefile.am:34: but option 'subdir-objects' is disabled
libpurple/Makefile.am:34: warning: source file 'media/candidate.c' is in a subdirectory,
libpurple/Makefile.am:34: but option 'subdir-objects' is disabled
libpurple/Makefile.am:34: warning: source file 'media/codec.c' is in a subdirectory,
libpurple/Makefile.am:34: but option 'subdir-objects' is disabled
libpurple/Makefile.am:34: warning: source file 'media/enum-types.c' is in a subdirectory,
libpurple/Makefile.am:34: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/common.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/dcc7.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/dcc.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/debug.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/deflate.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/encoding.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/endian.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/events.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/handlers.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/http.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/libgadu.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/message.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/network.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/obsolete.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/packets.pb-c.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/protobuf.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/protobuf-c.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/pubdir50.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/pubdir.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/resolver.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/sha1.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/tvbuff.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/gg/Makefile.am:49: warning: source file 'lib/tvbuilder.c' is in a subdirectory,
libpurple/protocols/gg/Makefile.am:49: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'google/gmail.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'google/google.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'google/google_presence.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'google/google_roster.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'google/google_session.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'google/jingleinfo.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'google/relay.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'jingle/jingle.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'jingle/content.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'jingle/iceudp.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'jingle/rawudp.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'jingle/rtp.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'jingle/session.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
libpurple/protocols/jabber/Makefile.am:8: warning: source file 'jingle/transport.c' is in a subdirectory,
libpurple/protocols/jabber/Makefile.am:8: but option 'subdir-objects' is disabled
configure: WARNING: unrecognized options: --enable-textui
checking build system type... i586-pc-haiku
checking host system type... i586-pc-haiku
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for sed... /bin/sed
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /boot/system/develop/tools/x86/i586-pc-haiku/bin/ld
checking if the linker (/boot/system/develop/tools/x86/i586-pc-haiku/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /boot/system/bin/x86/nm -B
checking the name lister (/boot/system/bin/x86/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 32768
checking how to convert i586-pc-haiku file names to i586-pc-haiku format... func_convert_file_noop
checking how to convert i586-pc-haiku file names to toolchain format... func_convert_file_noop
checking for /boot/system/develop/tools/x86/i586-pc-haiku/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /boot/system/bin/x86/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC...  -DPIC
checking if gcc PIC flag  -DPIC works... yes
checking if gcc static flag  works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/boot/system/develop/tools/x86/i586-pc-haiku/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... haiku runtime_loader
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /boot/system/bin/x86/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking whether __SUNPRO_C is declared... no
checking for ANSI C header files... (cached) yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking arpa/nameser_compat.h usability... yes
checking arpa/nameser_compat.h presence... yes
checking for arpa/nameser_compat.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking for stdint.h... (cached) yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking for an ANSI C-conforming const... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking size of time_t... 4
checking whether byte ordering is bigendian... no
checking return type of signal handlers... void
checking for strftime... yes
checking for strdup... yes
checking for strstr... yes
checking for atexit... yes
checking for setlocale... yes
checking for getopt_long... yes
checking for inet_aton... no
checking for inet_aton in -lnetwork... yes
checking for __res_query in -lnetwork... yes
checking for gethostent in -lnsl... no
checking for socket... yes
checking for getaddrinfo... yes
checking for inet_ntop... yes
checking for getifaddrs... yes
checking for socklen_t... yes
checking for struct sockaddr.sa_len... yes
checking whether IPV6_V6ONLY is declared... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for dlopen... yes
checking for library containing ceil... none required
checking for fileno()... yes
checking for the %z format string in strftime()... yes
checking whether NLS is requested... yes
checking for intltool-update... /bin/intltool-update
checking for intltool-merge... /bin/intltool-merge
checking for intltool-extract... /bin/intltool-extract
checking for xgettext... /boot/system/bin/x86/xgettext
checking for msgmerge... /boot/system/bin/x86/msgmerge
checking for msgfmt... /boot/system/bin/x86/msgfmt
checking for gmsgfmt... /boot/system/bin/x86/msgfmt
checking for perl... /bin/perl
checking for perl >= 5.8.1... 5.26.1
checking for XML::Parser... ok
checking for locale.h... (cached) yes
checking for LC_MESSAGES... yes
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... no
checking for bindtextdomain in -lintl... yes
checking for ngettext in -lintl... yes
checking for dgettext in -lintl... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /boot/system/bin/x86/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /boot/system/bin/x86/msgfmt
checking for xgettext... (cached) /boot/system/bin/x86/xgettext
checking for catalogs to be installed...  af am ar as ast az be@latin bg bn_IN bn br brx bs ca ca@valencia cs da de dz el en_AU en_CA en_GB eo es_AR es et eu fa fi fr ga gl gu he hi hr hu id it ja ka kk km kn ko ks ku_IQ ku lt lv mai mhr mk ml mn mr ms_MY my_MM nb ne nl nn oc or pa pl ps pt_BR pt ro ru sd si sk sl sq sr@latin sr sv sw ta te th tr tt uk ur uz vi xh zh_CN zh_HK zh_TW
checking for glib-2.0 >= 2.16.0 gobject-2.0 gmodule-2.0 gthread-2.0... yes
checking for X... no
checking for initscr in -lncursesw... yes
checking for update_panels in -lpanelw... yes
checking /boot/system/develop/headers//x86/ncurses.h usability... yes
checking /boot/system/develop/headers//x86/ncurses.h presence... yes
checking for /boot/system/develop/headers//x86/ncurses.h... yes
checking if /boot/system/develop/headers//x86/ncurses.h supports wide characters... yes
checking for libxml-2.0 >= 2.6.0... yes
checking for gconftool-2... no
./configure: line 18381: gconftool-2: command not found
Using config source  for schema installation
Using $(sysconfdir)/gconf/schemas as install directory for schema files
checking for farstream-0.1... no
checking for farsight2-0.10 >= 0.0.9... no
checking for libidn >= 0.0.0... yes
checking for silcclient >= 1.1... no
checking for silcclient... no
checking for silc... no
checking for libgadu >= 1.12.0... no
checking for gnutls_certificate_set_x509_system_trust in -lgnutls... no
checking for gnutls >= 2.10.0... no
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking for uname... yes
checking for -Waggregate-return option to gcc... yes
checking for -Wcast-align option to gcc... yes
checking for -Wdeclaration-after-statement option to gcc... yes
checking for -Wendif-labels option to gcc... yes
checking for -Werror-implicit-function-declaration option to gcc... yes
checking for -Wextra -Wno-unused-parameter option to gcc... yes
checking for -Wformat-security option to gcc... yes
checking for -Werror=format-security option to gcc... no
checking for -Winit-self option to gcc... yes
checking for -Wmissing-declarations option to gcc... yes
checking for -Wmissing-noreturn option to gcc... yes
checking for -Wmissing-prototypes option to gcc... yes
checking for -Wpointer-arith option to gcc... yes
checking for -Wundef option to gcc... yes
checking for FORTIFY_SOURCE support... no
checking for pidgin... no
checking for python... /bin/python
Building without D-Bus support
checking for Python compile flags... ok
checking for perl... /bin/perl
checking for Perl compile flags... ok
checking for libperl... checking for perl_run... yes
checking EXTERN.h usability... yes
checking EXTERN.h presence... yes
checking for EXTERN.h... yes
checking for perl.h... yes
checking for perl... perl
checking for perl module ExtUtils::MakeMaker... ok
checking for Perl_eval_pv... no
checking for old perl... no
checking for DynaLoader.a... no
checking for Mozilla nspr4 includes in /boot/system/develop/headers//x86... ""
checking nspr.h usability... no
checking nspr.h presence... yes
configure: WARNING: nspr.h: present but cannot be compiled
configure: WARNING: nspr.h:     check for missing prerequisite headers?
configure: WARNING: nspr.h: see the Autoconf documentation
configure: WARNING: nspr.h:     section "Present But Cannot Be Compiled"
configure: WARNING: nspr.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------ ##
configure: WARNING:     ## Report this to devel@pidgin.im ##
configure: WARNING:     ## ------------------------------ ##
checking for nspr.h... no
checking prio.h usability... no
checking prio.h presence... yes
configure: WARNING: prio.h: present but cannot be compiled
configure: WARNING: prio.h:     check for missing prerequisite headers?
configure: WARNING: prio.h: see the Autoconf documentation
configure: WARNING: prio.h:     section "Present But Cannot Be Compiled"
configure: WARNING: prio.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------ ##
configure: WARNING:     ## Report this to devel@pidgin.im ##
configure: WARNING:     ## ------------------------------ ##
checking for prio.h... no
checking for Mozilla nspr4 libraries... no
checking for Mozilla nss3 includes... no
checking for Mozilla nss libraries... no
configure: error: 
NSS SSL development headers not found.
Use --disable-nss if you do not need SSL support.
Novell Groupwise and Google Talk will not work without SSL support.

Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 1
Error: Build has failed - stopping.
~>

**Comment by alaviss** [comment]
Hi, please consider wrapping console outputs in <code>```</code> blocks. It will avoid Github's Markdown formatting and disable line wrapping, making the console log easier to read.

**Comment by pulkomandy** [comment]
Fixed in 075f3a7cfed, but I hit other failures in libpurple (mostly, it needs a libpython and we don't provide one). I tried adjusting it for python3 but then glib build tools have problems.

**Comment by Begasus** [comment]
Problem is still here, just checked with gcc2h _x86 and nspr-4.19_x86 installed

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/6027
