### ISSUE TITLE
Cannot open Generic projects in Qt Creator unless started from Terminal at least once

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#3554]
- Try creating a "Generic" (Imported) project; it never opens, even ones that opened in previous versions. Nothing happens.
 - After trying to do this, save any open file twice. Crash!

**Comment by korli** [comment]
are you on 4.8.0?

**Comment by threedeyes** [comment]
QtCreator was updated before Qt bumping to 5.12.0 version. I thuink we need rebuild qtcreator package with actial Qt version.

**Comment by waddlesplash** [comment]
Nope, exact same behavior.

Here's a crash report that occured after hitting Save on an open file three times:
<details>

```
Debug information for team /boot/system/apps/QtCreator/bin/Qt Creator (803):
CPU(s): 4x Intel Core™ i3-5005U
Memory: 7.92 GiB total, 562.11 MiB used
Haiku revision: hrev52762 Jan 15 2019 05:39:30 (x86_64)

Active Threads:
	thread 806: BApplication_thread 
	thread 807: pthread func 
	thread 808: pthread func 
	thread 809: pthread func 
	thread 905: w>freebsd_network.files - Qt Cr 
	thread 931: w>QtCreator 
	thread 945: w>QtCreator 
	thread 1395: team 803 debug task 
	thread 803: Qt Creator (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7fd7fa7131f0	0x1575141c988	ProjectExplorer::Project::emitParsingStarted() + 0x8 
			Disassembly:
				ProjectExplorer::Project::emitParsingStarted():
				0x000001575141c980:               55  push %rbp
				0x000001575141c981:         488b4710  mov 0x10(%rdi), %rax
				0x000001575141c985:           4889e5  mov %rsp, %rbp
				0x000001575141c988:         80780800  cmp $0x0, 0x8(%rax) <--

			Frame memory:
				[0x7fd7fa7131e0]  .2q........K....   b0 32 71 fa d7 7f 00 00 de ea b4 4b 88 00 00 00
		0x7fd7fa7132c0	0x884bb4ead9	GenericProjectManager::Internal::GenericProject::refresh(GenericProjectManager::Internal::GenericProject::RefreshOptions) + 0x19 
		0x7fd7fa7132d0	0x1575141beb2	ProjectExplorer::ProjectDocument::reload(QString*, Core::IDocument::ReloadFlag, Core::IDocument::ChangeType) + 0x12 
		0x7fd7fa7134b0	0x18bdfb2f4d2	Core::DocumentManager::checkForReload() + 0x1792 
		0x7fd7fa7134e0	0xdabc1e7581	QSingleShotTimer::timerEvent(QTimerEvent*) + 0x71 
		0x7fd7fa713560	0xdabc1db4a9	QObject::event(QEvent*) + 0x79 
		0x7fd7fa713590	0xca666cd599	QApplicationPrivate::notify_helper(QObject*, QEvent*) + 0x99 
		0x7fd7fa7136f0	0xca666d47dd	QApplication::notify(QObject*, QEvent*) + 0x2cd 
		0x7fd7fa713770	0xdabc1ab686	QCoreApplication::notifyInternal2(QObject*, QEvent*) + 0xf6 
		0x7fd7fa713810	0xdabc205df4	QTimerInfoList::activateTimers() + 0x3d4 
		0x7fd7fa713820	0xdabc20652c	timerSourceDispatch(_GSource*, int (*)(void*), void*) + 0x1c 
		0x7fd7fa713890	0x1ca3168d9a	g_main_dispatch + 0x19a 
		0x7fd7fa7138b0	0x1ca3169c1e	g_main_context_dispatch + 0x2e 
		0x7fd7fa713910	0x1ca3169e02	g_main_context_iterate + 0x1d0 
		0x7fd7fa713940	0x1ca3169ec6	g_main_context_iteration + 0x45 
		0x7fd7fa7139a0	0xdabc2068bc	QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 0x5c 
		0x7fd7fa713a20	0xdabc1a9f66	QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 0x126 
		0x7fd7fa713a70	0xdabc1b2a51	QCoreApplication::exec() + 0x81 
		0x7fd7fa713d70	0x11ff8ec36d3	main + 0x2543 
		0x7fd7fa713da0	0x11ff8ec3fdc	_start + 0x4c 
		0x7fd7fa713dd0	0xdb15899200	runtime_loader + 0x100 
		00000000	0x7f354e0fb260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x000001575141c988
			  rsp:	0x00007fd7fa7131e0
			  rbp:	0x00007fd7fa7131e0
			  rax:	0x0000000000000018
			  rbx:	0x0000000000000001
			  rcx:	0x0000000000000000
			  rdx:	0x0000000000000000
			  rsi:	0x0000000000000001
			  rdi:	0x000001c4c171c1e0
			   r8:	0x00000157517fcfe8
			   r9:	0x0000000000000000
			  r10:	0x0000000000000007
			  r11:	0x000001c4c0df14ea
			  r12:	0x00007fd7fa713450
			  r13:	0x00007fd7fa713430
			  r14:	0x000001c4c171c1e0
			  r15:	0x0000000000000001
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff}
			 xmm3:	{0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff}
			 xmm4:	{0x62, 0x73, 0x64, 0x5f, 0x6e, 0x65, 0x74, 0x77}
			 xmm5:	{0x6f, 0x72, 0x6b, 0x2e, 0x66, 0x69, 0x6c, 0x65}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	3355	0x1286ac000	0x1287b0000	0x1289b0000	0x1289b6000	lib    	/boot/system/lib/libsqlite3.so.0.8.6
	3314	0x8ce0df000	0x8ce2b4000	0x8ce4b4000	0x8ce4c4000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libCppTools.so
	3366	0x13b5b50000	0x13b5bd0000	0x13b5dcf000	0x13b5dd2000	lib    	/boot/system/add-ons/Qt5/imageformats/libqwebp.so
	3269	0x17d3160000	0x17d32c8000	0x17d34c8000	0x17d34dc000	lib    	/boot/system/lib/libstdc++.so.6.0.24
	3351	0x19dae24000	0x19dae5c000	0x19db05b000	0x19db05e000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libTodo.so
	3291	0x1ab90df000	0x1ab91c3000	0x1ab93c2000	0x1ab93c4000	lib    	/boot/system/lib/libiconv.so.2.6.0
	3361	0x1c0f48e000	0x1c0f493000	0x1c0f692000	0x1c0f693000	lib    	/boot/system/add-ons/Qt5/imageformats/libqsvg.so
	3283	0x1ca3112000	0x1ca323c000	0x1ca343b000	0x1ca343d000	lib    	/boot/system/lib/libglib-2.0.so.0.5701.0
	3325	0x25850c8000	0x2585103000	0x2585303000	0x2585306000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libAutotoolsProjectManager.so
	3343	0x2c1623a000	0x2c16271000	0x2c16470000	0x2c16472000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libMacros.so
	3347	0x3a2dcc5000	0x3a2dd55000	0x3a2df54000	0x3a2df5b000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libRemoteLinux.so
	3344	0x512bde8000	0x512be40000	0x512c03f000	0x512c043000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libModelEditor.so
	3360	0x51f2104000	0x51f213d000	0x51f233d000	0x51f233e000	lib    	/boot/system/lib/libjpeg.so.9.3.0
	3340	0x53c3ad1000	0x53c3af2000	0x53c3cf2000	0x53c3cf4000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libImageViewer.so
	3335	0x5725dd8000	0x5725df6000	0x5725ff6000	0x5725ff8000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libGLSLEditor.so
	3349	0x59c052d000	0x59c062a000	0x59c0829000	0x59c0838000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libScxmlEditor.so
	3308	0x5d5d299000	0x5d5d2df000	0x5d5d4df000	0x5d5d4e1000	lib    	/boot/system/lib/libQt5Sql.so.5.12.0
	3367	0x64fccee000	0x64fccf6000	0x64fcef6000	0x64fcef7000	lib    	/boot/system/add-ons/Qt5/iconengines/libqsvgicon.so
	3341	0x664a820000	0x664a872000	0x664aa72000	0x664aa75000	lib    	/boot/system/lib/libQt5Svg.so.5.12.0
	3323	0x6a0d6cc000	0x6a0d844000	0x6a0da43000	0x6a0da52000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libQmlJS.so.4.8.0
	3309	0x6a5c6e3000	0x6a5c8cc000	0x6a5cacb000	0x6a5cb01000	lib    	/boot/system/lib/libQt5Script.so.5.12.0
	3298	0x6a63855000	0x6a63893000	0x6a63a92000	0x6a63a98000	lib    	/boot/system/lib/libfontconfig.so.1.10.1
	3339	0x7099120000	0x7099183000	0x7099382000	0x7099385000	lib    	/boot/system/lib/libQt5Help.so.5.12.0
	3296	0x72aeef2000	0x72aef39000	0x72af138000	0x72af13c000	lib    	/boot/system/add-ons/Qt5/platforms/libqhaiku.so
	3277	0x740f36e000	0x740f5eb000	0x740f7ea000	0x740f7ff000	lib    	/boot/system/lib/libicui18n.so.57.1
	3324	0x7af68c6000	0x7af69f8000	0x7af6bf8000	0x7af6c03000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libAndroid.so
	3270	0x7bd54c8000	0x7bd54dd000	0x7bd56dc000	0x7bd56dd000	lib    	/boot/system/lib/libgcc_s.so.1
	3365	0x7fbdc73000	0x7fbdc77000	0x7fbde76000	0x7fbde77000	lib    	/boot/system/add-ons/Qt5/imageformats/libqwbmp.so
	3268	0x7fbeb1a000	0x7fbebac000	0x7fbedac000	0x7fbedbf000	lib    	/boot/system/lib/libGL.so.1.0.0
	3264	0x80cb0ca000	0x80cb6b0000	0x80cb8b0000	0x80cb8cd000	lib    	/boot/system/lib/libQt5Gui.so.5.12.0
	3337	0x884bb3b000	0x884bb69000	0x884bd68000	0x884bd6b000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libGenericProjectManager.so
	3307	0x8de1258000	0x8de12b6000	0x8de14b5000	0x8de14ba000	lib    	/boot/system/lib/libQt5PrintSupport.so.5.12.0
	3305	0x9582ce5000	0x9582d06000	0x9582f05000	0x9582f07000	lib    	/boot/system/add-ons/Qt5/styles/libqhaikustyle.so
	3334	0x9eb01ec000	0x9eb0266000	0x9eb0466000	0x9eb0469000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libFakeVim.so
	3315	0xa457ad5000	0xa457cf2000	0xa457ef1000	0xa457f39000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libCPlusPlus.so.4.8.0
	3311	0xa497700000	0xa497739000	0xa497938000	0xa49793a000	lib    	/boot/system/lib/libQt5Xml.so.5.12.0
	3288	0xa7ea2b2000	0xa7ea2e1000	0xa7ea4e1000	0xa7ea515000	lib    	/boot/system/lib/libicutu.so.57.1
	3304	0xaa9271b000	0xaa92817000	0xaa92a17000	0xaa92a1a000	lib    	/boot/system/lib/libtextencoding.so
	3279	0xab235e1000	0xab24e5f000	0xab2505e000	0xab2505f000	lib    	/boot/system/lib/libicudata.so.57.1
	3276	0xac000ca000	0xac0010b000	0xac0030a000	0xac00313000	lib    	/boot/system/lib/libnetwork.so
	3336	0xafa326d000	0xafa32b6000	0xafa34b6000	0xafa34bd000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libGLSL.so.4.8.0
	3330	0xb0c9c12000	0xb0c9e76000	0xb0ca076000	0xb0ca091000	lib    	/boot/system/lib/libQt5DesignerComponents.so.5.12.0
	3362	0xb7d7969000	0xb7d796d000	0xb7d7b6d000	0xb7d7b6e000	lib    	/boot/system/add-ons/Qt5/imageformats/libqtga.so
	3333	0xbabe3a7000	0xbabe3c8000	0xbabe5c8000	0xbabe5ca000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libClassView.so
	3297	0xc28c8ae000	0xc28ca48000	0xc28cc48000	0xc28cc61000	lib    	/boot/system/lib/libtracker.so
	3321	0xc372a84000	0xc372a91000	0xc372c91000	0xc372c92000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libLanguageUtils.so.4.8.0
	3282	0xc5a3fa3000	0xc5a3fa4000	0xc5a41a3000	0xc5a41a4000	lib    	/boot/system/lib/libgthread-2.0.so.0.5701.0
	3263	0xca66572000	0xca66b6e000	0xca66d6e000	0xca66da0000	lib    	/boot/system/lib/libQt5Widgets.so.5.12.0
	3331	0xcd67a41000	0xcd67f2d000	0xcd6812d000	0xcd68146000	lib    	/boot/system/lib/libQt5Designer.so.5.12.0
	3262	0xcf42cdf000	0xcf42edb000	0xcf430db000	0xcf430f0000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libUtils.so.4.8.0
	3358	0xcfed19d000	0xcfed1a3000	0xcfed3a3000	0xcfed3a4000	lib    	/boot/system/add-ons/Qt5/imageformats/libqico.so
	3342	0xd019495000	0xd0195bc000	0xd0197bc000	0xd0197c6000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libQmakeProjectManager.so
	3319	0xd12ba34000	0xd12bb2e000	0xd12bd2d000	0xd12bd3c000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libCppEditor.so
	3261	0xd24ca4a000	0xd24ca4f000	0xd24cc4e000	0xd24cc4f000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libAggregation.so.4.8.0
	3267	0xdabbf3f000	0xdabc431000	0xdabc631000	0xdabc642000	lib    	/boot/system/lib/libQt5Core.so.5.12.0
	3346	0xdaf96cb000	0xdaf96ea000	0xdaf98ea000	0xdaf98ec000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libPythonEditor.so
	3258	0xdb15885000	0xdb158a7000	0xdb15aa6000	0xdb15aa8000	lib    	/boot/system/runtime_loader
	3338	0xe458125000	0xe4581be000	0xe4583be000	0xe4583c5000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libHelp.so
	3353	0xf2a5a3c000	0xf2a5a4d000	0xf2a5c4d000	0xf2a5c4e000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libWelcome.so
	3287	0xfb36a66000	0xfb36a71000	0xfb36c71000	0xfb36c72000	lib    	/boot/system/lib/libiculx.so.57.1
	3280	0x106a3c0d000	0x106a3c82000	0x106a3e81000	0x106a3e82000	lib    	/boot/system/lib/libpcre2-16.so.0.6.0
	3302	0x10d3b371000	0x10d3b4d0000	0x10d3b6cf000	0x10d3b6dc000	lib    	/boot/system/lib/libxml2.so.2.9.7
	3273	0x10d6d665000	0x10d6d97a000	0x10d6db7a000	0x10d6dba8000	lib    	/boot/system/lib/libbe.so
	3363	0x118f1e9f000	0x118f1ea7000	0x118f20a6000	0x118f20a7000	lib    	/boot/system/add-ons/Qt5/imageformats/libqtiff.so
	3326	0x11a2dbf9000	0x11a2dc35000	0x11a2de34000	0x11a2de37000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libCodePaster.so
	3316	0x11ace38c000	0x11ace3cd000	0x11ace5cd000	0x11ace5d0000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libResourceEditor.so
	3259	0x11ff8eb6000	0x11ff8ed1000	0x11ff90d1000	0x11ff90d2000	app    	/boot/system/apps/QtCreator/bin/Qt Creator
	3364	0x12693579000	0x126935e9000	0x126937e8000	0x126937ec000	lib    	/boot/system/lib/libtiff.so.5.4.0
	3328	0x13a4cffd000	0x13a4d01f000	0x13a4d21f000	0x13a4d221000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libBookmarks.so
	3350	0x14adaca1000	0x14adaca9000	0x14adaea8000	0x14adaea9000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libTaskList.so
	3368	0x14e1c0fc000	0x14e1c115000	0x14e1c314000	0x14e1c315000	lib    	/boot/system/add-ons/Qt5/bearer/libqgenericbearer.so
	3332	0x14e5fb48000	0x14e5fc49000	0x14e5fe49000	0x14e5fe50000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libCMakeProjectManager.so
	3322	0x1550b220000	0x1550b24f000	0x1550b44f000	0x1550b451000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libQmlDebug.so.4.8.0
	3320	0x156005a3000	0x15600871000	0x15600a70000	0x15600a87000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libDebugger.so
	3312	0x157511ea000	0x157515f9000	0x157517f8000	0x1575181d000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libProjectExplorer.so
	3359	0x169d6440000	0x169d644a000	0x169d6649000	0x169d664a000	lib    	/boot/system/add-ons/Qt5/imageformats/libqjpeg.so
	3354	0x16ff70f1000	0x16ff7102000	0x16ff7302000	0x16ff7303000	lib    	/boot/system/add-ons/Qt5/sqldrivers/libqsqlite.so
	3352	0x170b8633000	0x170b86d6000	0x170b88d5000	0x170b88db000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libValgrind.so
	3299	0x171093e1000	0x1710948e000	0x1710968e000	0x17109695000	lib    	/boot/system/lib/libfreetype.so.6.16.1
	3345	0x183b50e4000	0x183b52d3000	0x183b54d2000	0x183b54e4000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libModeling.so.4.8.0
	3290	0x1844dda8000	0x1844ddaf000	0x1844dfaf000	0x1844dfb0000	lib    	/boot/system/lib/libbsd.so
	3289	0x18456b6c000	0x18456c35000	0x18456e35000	0x18456e36000	lib    	/boot/system/lib/libzstd.so.1.3.7
	3356	0x187d8cdb000	0x187d8ce2000	0x187d8ee1000	0x187d8ee2000	lib    	/boot/system/add-ons/Qt5/imageformats/libqgif.so
	3306	0x18bdf97d000	0x18bdfc33000	0x18bdfe32000	0x18bdfe4d000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libCore.so
	3284	0x1908b8c8000	0x1908b8d1000	0x1908bad1000	0x1908bad2000	lib    	/boot/system/lib/libintl.so.8.1.5
	3292	0x192e6daa000	0x192e6ded000	0x192e6fed000	0x192e6fee000	lib    	/boot/system/lib/libpcre.so.1.2.10
	3275	0x1944bbf4000	0x1944bc10000	0x1944be0f000	0x1944be10000	lib    	/boot/system/lib/libz.so.1.2.11
	3271	0x19e4ec52000	0x19e4edb1000	0x19e4efb0000	0x19e4f003000	lib    	/boot/system/lib/libroot.so
	3265	0x1a04d276000	0x1a04d27b000	0x1a04d47b000	0x1a04d47c000	lib    	/boot/system/lib/libQt5Concurrent.so.5.12.0
	3301	0x1ac9a998000	0x1ac9a9ad000	0x1ac9abac000	0x1ac9abae000	lib    	/boot/system/lib/libtranslation.so
	3313	0x1b248683000	0x1b24885c000	0x1b248a5c000	0x1b248a6d000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libQtcSsh.so.4.8.0
	3310	0x1b4e15f5000	0x1b4e1809000	0x1b4e1a08000	0x1b4e1a18000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libTextEditor.so
	3318	0x1bcf225f000	0x1bcf2283000	0x1bcf2483000	0x1bcf2485000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libBinEditor.so
	3295	0x1bd0962e000	0x1bd0963f000	0x1bd0983f000	0x1bd09840000	lib    	/boot/system/lib/libroot-addon-icu.so
	3348	0x1c4371b3000	0x1c437222000	0x1c437421000	0x1c437426000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libQnx.so
	3303	0x1d4d7c6c000	0x1d4d7c7b000	0x1d4d7e7a000	0x1d4d7e7c000	lib    	/boot/system/lib/libbz2.so.1.0.6
	3281	0x1d5588fa000	0x1d558906000	0x1d558b05000	0x1d558b06000	lib    	/boot/system/lib/libdouble-conversion.so.1.0.0
	3278	0x1daec52f000	0x1daec6c7000	0x1daec8c6000	0x1daec8db000	lib    	/boot/system/lib/libicuuc.so.57.1
	3327	0x1dc6b9a3000	0x1dc6ba0a000	0x1dc6bc0a000	0x1dc6bc0e000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libDiffEditor.so
	3274	0x1dc7f9f3000	0x1dc7fa24000	0x1dc7fc24000	0x1dc7fc25000	lib    	/boot/system/lib/libpng16.so.16.35.0
	3286	0x1e63cbd8000	0x1e63cc2d000	0x1e63ce2d000	0x1e63ce30000	lib    	/boot/system/lib/libicule.so.57.1
	3266	0x1e8b8bcf000	0x1e8b8d5a000	0x1e8b8f5a000	0x1e8b8f63000	lib    	/boot/system/lib/libQt5Network.so.5.12.0
	3357	0x1eb24cc8000	0x1eb24cd1000	0x1eb24ed0000	0x1eb24ed1000	lib    	/boot/system/add-ons/Qt5/imageformats/libqicns.so
	3260	0x1f0172e7000	0x1f017326000	0x1f017525000	0x1f017528000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/libExtensionSystem.so.4.8.0
	3329	0x1f67a328000	0x1f67a375000	0x1f67a574000	0x1f67a579000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libDesigner.so
	3317	0x1f820b74000	0x1f820c6a000	0x1f820e69000	0x1f820e70000	lib    	/boot/system/apps/QtCreator/lib/qtcreator/plugins/libQtSupport.so
	3300	0x200814c2000	0x2008154c000	0x2008174c000	0x2008174f000	lib    	/boot/system/lib/libQt5DBus.so.5.12.0
	3285	0x23542a09000	0x23542a15000	0x23542c14000	0x23542c16000	lib    	/boot/system/lib/libicuio.so.57.1
	3272	0x252e4896000	0x252e4cbe000	0x252e4ebe000	0x252e4ede000	lib    	/boot/system/lib/libQt5Qml.so.5.12.0
	3257	0x7f354e0fb000	0x7f354e103000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	24187	0x00138000	0x001a8000	       448	r--        	full          	mmap area
	24189	0x001bc000	0x00225000	       420	r--        	full          	mmap area
	23460	0x0023b000	0x002ab000	       448	r--        	full          	mmap area
	24193	0x002c7000	0x00348000	       516	r--        	full          	mmap area
	24192	0x0034f000	0x003d6000	       540	r--        	full          	mmap area
	24191	0x007c4000	0x00803000	       252	r--        	full          	mmap area
	22432	0x0083e000	0x00859000	       108	r--        	full          	mmap area
	10205	0x00914000	0x00924000	        64	rwx        	full          	mmap area
	24188	0x00dc9000	0x01d74000	     16044	r--        	full          	mmap area
	10028	0x029ed000	0x02a21000	       208	r--        	full          	mmap area
	24190	0x02a65000	0x03a10000	     16044	r--        	full          	mmap area
	9994	0x047a4000	0x04814000	       448	r--        	full          	mmap area
	9890	0x0d2da000	0x0d2db000	         4	rw-        	full          	mmap area
	9889	0x30443000	0x30843000	      4096	rw-        	full          	mmap area
	9887	0x4ba3e000	0x4ba3f000	         4	   rw-     	full          	mmap area
	9886	0x4ba3f000	0x4bc3d000	      2040	rw-        	full          	mmap area
	9888	0x4bc3d000	0x4bc3e000	         4	   rw-     	full          	mmap area
	9884	0x5335f000	0x53360000	         4	   rw-     	full          	mmap area
	9883	0x53360000	0x5379e000	      4344	rw-        	full          	mmap area
	9885	0x5379e000	0x5379f000	         4	   rw-     	full          	mmap area
	9705	0x5be18000	0x5be19000	         4	rw-S       	full          	mmap area
	9597	0x60000000	0x60001000	         4	rw-S       	full          	server_memory
	9599	0x68000000	0x68027000	       156	rw-S       	full          	server_memory
	21874	0x70000000	0x70460000	      4480	rw-S       	full          	server_memory
	9881	0x1286ac000	0x1287b0000	      1040	r-x        	full          	libsqlite3.so.0.8.6_seg0ro
	9882	0x1289b0000	0x1289b6000	        24	rw-        	full          	libsqlite3.so.0.8.6_seg1rw
	9557	0x31b0e0000	0x31b0f8000	        96	rw-        	full          	rld heap
	9556	0x506f1f000	0x506f37000	        96	rw-        	full          	rld heap
	9555	0x649b2d000	0x649b3d000	        64	rw-        	full          	rld heap
	9797	0x8ce0df000	0x8ce2b4000	      1876	r-x        	full          	libCppTools.so_seg0ro
	9798	0x8ce4b4000	0x8ce4c4000	        64	rw-        	full          	libCppTools.so_seg1rw
	9554	0x9e6eac000	0x9e6ebc000	        64	rw-        	full          	rld heap
	9553	0xb85a69000	0xb85a71000	        32	rw-        	full          	rld heap
	9546	0xd68d0a000	0xd68d12000	        32	rw-        	full          	rld heap
	10024	0x13b5b50000	0x13b5bd0000	       512	r-x        	full          	libqwebp.so_seg0ro
	10025	0x13b5dcf000	0x13b5dd0000	         4	rw-        	full          	libqwebp.so_seg1rw
	10026	0x13b5dd0000	0x13b5dd2000	         8	rw-        	full          	libqwebp.so_seg2rw
	9499	0x17d3160000	0x17d32c8000	      1440	r-x        	full          	libstdc++.so.6.0.24_seg0ro
	9500	0x17d34c8000	0x17d34d4000	        48	rw-        	full          	libstdc++.so.6.0.24_seg1rw
	9501	0x17d34d4000	0x17d34dc000	        32	rw-        	full          	libstdc++.so.6.0.24_seg2rw
	9872	0x19dae24000	0x19dae5c000	       224	r-x        	full          	libTodo.so_seg0ro
	9873	0x19db05b000	0x19db05e000	        12	rw-        	full          	libTodo.so_seg1rw
	9549	0x1ab90df000	0x1ab91c3000	       912	r-x        	full          	libiconv.so.2.6.0_seg0ro
	9550	0x1ab93c2000	0x1ab93c4000	         8	rw-        	full          	libiconv.so.2.6.0_seg1rw
	10014	0x1c0f48e000	0x1c0f493000	        20	r-x        	full          	libqsvg.so_seg0ro
	10015	0x1c0f692000	0x1c0f693000	         4	rw-        	full          	libqsvg.so_seg1rw
	9531	0x1ca3112000	0x1ca323c000	      1192	r-x        	full          	libglib-2.0.so.0.5701.0_seg0ro
	9532	0x1ca343b000	0x1ca343d000	         8	rw-        	full          	libglib-2.0.so.0.5701.0_seg1rw
	9473	0x1f6a594000	0x1f6a595000	         4	rw-S       	full          	_rld_debug_
	9819	0x25850c8000	0x2585103000	       236	r-x        	full          	libAutotoolsProjectManager.so_s
	9820	0x2585303000	0x2585306000	        12	rw-        	full          	libAutotoolsProjectManager.so_s
	9472	0x2587791000	0x25877a1000	        64	rw-        	full          	rld heap
	9855	0x2c1623a000	0x2c16271000	       220	r-x        	full          	libMacros.so_seg0ro
	9856	0x2c16470000	0x2c16472000	         8	rw-        	full          	libMacros.so_seg1rw
	9864	0x3a2dcc5000	0x3a2dd55000	       576	r-x        	full          	libRemoteLinux.so_seg0ro
	9865	0x3a2df54000	0x3a2df5b000	        28	rw-        	full          	libRemoteLinux.so_seg1rw
	9857	0x512bde8000	0x512be40000	       352	r-x        	full          	libModelEditor.so_seg0ro
	9858	0x512c03f000	0x512c043000	        16	rw-        	full          	libModelEditor.so_seg1rw
	10012	0x51f2104000	0x51f213d000	       228	r-x        	full          	libjpeg.so.9.3.0_seg0ro
	10013	0x51f233d000	0x51f233e000	         4	rw-        	full          	libjpeg.so.9.3.0_seg1rw
	9849	0x53c3ad1000	0x53c3af2000	       132	r-x        	full          	libImageViewer.so_seg0ro
	9850	0x53c3cf2000	0x53c3cf4000	         8	rw-        	full          	libImageViewer.so_seg1rw
	9839	0x5725dd8000	0x5725df6000	       120	r-x        	full          	libGLSLEditor.so_seg0ro
	9840	0x5725ff6000	0x5725ff8000	         8	rw-        	full          	libGLSLEditor.so_seg1rw
	9868	0x59c052d000	0x59c062a000	      1012	r-x        	full          	libScxmlEditor.so_seg0ro
	9869	0x59c0829000	0x59c0838000	        60	rw-        	full          	libScxmlEditor.so_seg1rw
	9783	0x5d5d299000	0x5d5d2df000	       280	r-x        	full          	libQt5Sql.so.5.12.0_seg0ro
	9784	0x5d5d4df000	0x5d5d4e1000	         8	rw-        	full          	libQt5Sql.so.5.12.0_seg1rw
	10030	0x64fccee000	0x64fccf6000	        32	r-x        	full          	libqsvgicon.so_seg0ro
	10031	0x64fcef6000	0x64fcef7000	         4	rw-        	full          	libqsvgicon.so_seg1rw
	9851	0x664a820000	0x664a872000	       328	r-x        	full          	libQt5Svg.so.5.12.0_seg0ro
	9852	0x664aa72000	0x664aa75000	        12	rw-        	full          	libQt5Svg.so.5.12.0_seg1rw
	9815	0x6a0d6cc000	0x6a0d844000	      1504	r-x        	full          	libQmlJS.so.4.8.0_seg0ro
	9816	0x6a0da43000	0x6a0da52000	        60	rw-        	full          	libQmlJS.so.4.8.0_seg1rw
	9785	0x6a5c6e3000	0x6a5c8cc000	      1956	r-x        	full          	libQt5Script.so.5.12.0_seg0ro
	9786	0x6a5cacb000	0x6a5cade000	        76	rw-        	full          	libQt5Script.so.5.12.0_seg1rw
	9787	0x6a5cade000	0x6a5cb01000	       140	rw-        	full          	libQt5Script.so.5.12.0_seg2rw
	9577	0x6a63855000	0x6a63893000	       248	r-x        	full          	libfontconfig.so.1.10.1_seg0ro
	9578	0x6a63a92000	0x6a63a98000	        24	rw-        	full          	libfontconfig.so.1.10.1_seg1rw
	9847	0x7099120000	0x7099183000	       396	r-x        	full          	libQt5Help.so.5.12.0_seg0ro
	9848	0x7099382000	0x7099385000	        12	rw-        	full          	libQt5Help.so.5.12.0_seg1rw
	9572	0x72aeef2000	0x72aef39000	       284	r-x        	full          	libqhaiku.so_seg0ro
	9573	0x72af138000	0x72af13c000	        16	rw-        	full          	libqhaiku.so_seg1rw
	9519	0x740f36e000	0x740f5eb000	      2548	r-x        	full          	libicui18n.so.57.1_seg0ro
	9520	0x740f7ea000	0x740f7ff000	        84	rw-        	full          	libicui18n.so.57.1_seg1rw
	9817	0x7af68c6000	0x7af69f8000	      1224	r-x        	full          	libAndroid.so_seg0ro
	9818	0x7af6bf8000	0x7af6c03000	        44	rw-        	full          	libAndroid.so_seg1rw
	9502	0x7bd54c8000	0x7bd54dd000	        84	r-x        	full          	libgcc_s.so.1_seg0ro
	9503	0x7bd56dc000	0x7bd56dd000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	10022	0x7fbdc73000	0x7fbdc77000	        16	r-x        	full          	libqwbmp.so_seg0ro
	10023	0x7fbde76000	0x7fbde77000	         4	rw-        	full          	libqwbmp.so_seg1rw
	9496	0x7fbeb1a000	0x7fbebac000	       584	r-x        	full          	libGL.so.1.0.0_seg0ro
	9497	0x7fbedac000	0x7fbedbd000	        68	rw-        	full          	libGL.so.1.0.0_seg1rw
	9498	0x7fbedbd000	0x7fbedbf000	         8	rw-        	full          	libGL.so.1.0.0_seg2rw
	9485	0x80cb0ca000	0x80cb6b0000	      6040	r-x        	full          	libQt5Gui.so.5.12.0_seg0ro
	9486	0x80cb8b0000	0x80cb8c6000	        88	rw-        	full          	libQt5Gui.so.5.12.0_seg1rw
	9487	0x80cb8c6000	0x80cb8cd000	        28	rw-        	full          	libQt5Gui.so.5.12.0_seg2rw
	9843	0x884bb3b000	0x884bb69000	       184	r-x        	full          	libGenericProjectManager.so_seg
	9844	0x884bd68000	0x884bd6b000	        12	rw-        	full          	libGenericProjectManager.so_seg
	9781	0x8de1258000	0x8de12b6000	       376	r-x        	full          	libQt5PrintSupport.so.5.12.0_se
	9782	0x8de14b5000	0x8de14ba000	        20	rw-        	full          	libQt5PrintSupport.so.5.12.0_se
	9703	0x9582ce5000	0x9582d06000	       132	r-x        	full          	libqhaikustyle.so_seg0ro
	9704	0x9582f05000	0x9582f07000	         8	rw-        	full          	libqhaikustyle.so_seg1rw
	9837	0x9eb01ec000	0x9eb0266000	       488	r-x        	full          	libFakeVim.so_seg0ro
	9838	0x9eb0466000	0x9eb0469000	        12	rw-        	full          	libFakeVim.so_seg1rw
	9799	0xa457ad5000	0xa457cf2000	      2164	r-x        	full          	libCPlusPlus.so.4.8.0_seg0ro
	9800	0xa457ef1000	0xa457f39000	       288	rw-        	full          	libCPlusPlus.so.4.8.0_seg1rw
	9790	0xa497700000	0xa497739000	       228	r-x        	full          	libQt5Xml.so.5.12.0_seg0ro
	9791	0xa497938000	0xa49793a000	         8	rw-        	full          	libQt5Xml.so.5.12.0_seg1rw
	9541	0xa7ea2b2000	0xa7ea2e1000	       188	r-x        	full          	libicutu.so.57.1_seg0ro
	9542	0xa7ea4e1000	0xa7ea4e3000	         8	rw-        	full          	libicutu.so.57.1_seg1rw
	9543	0xa7ea4e3000	0xa7ea515000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	9591	0xaa9271b000	0xaa92817000	      1008	r-x        	full          	libtextencoding.so_seg0ro
	9592	0xaa92a17000	0xaa92a1a000	        12	rw-        	full          	libtextencoding.so_seg1rw
	9523	0xab235e1000	0xab24e5f000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	9524	0xab2505e000	0xab2505f000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	9516	0xac000ca000	0xac0010b000	       260	r-x        	full          	libnetwork.so_seg0ro
	9517	0xac0030a000	0xac0030d000	        12	rw-        	full          	libnetwork.so_seg1rw
	9518	0xac0030d000	0xac00313000	        24	rw-        	full          	libnetwork.so_seg2rw
	9841	0xafa326d000	0xafa32b6000	       292	r-x        	full          	libGLSL.so.4.8.0_seg0ro
	9842	0xafa34b6000	0xafa34bd000	        28	rw-        	full          	libGLSL.so.4.8.0_seg1rw
	9829	0xb0c9c12000	0xb0c9e76000	      2448	r-x        	full          	libQt5DesignerComponents.so.5.1
	9830	0xb0ca076000	0xb0ca091000	       108	rw-        	full          	libQt5DesignerComponents.so.5.1
	10016	0xb7d7969000	0xb7d796d000	        16	r-x        	full          	libqtga.so_seg0ro
	10017	0xb7d7b6d000	0xb7d7b6e000	         4	rw-        	full          	libqtga.so_seg1rw
	9835	0xbabe3a7000	0xbabe3c8000	       132	r-x        	full          	libClassView.so_seg0ro
	9836	0xbabe5c8000	0xbabe5ca000	         8	rw-        	full          	libClassView.so_seg1rw
	9574	0xc28c8ae000	0xc28ca48000	      1640	r-x        	full          	libtracker.so_seg0ro
	9575	0xc28cc48000	0xc28cc60000	        96	rw-        	full          	libtracker.so_seg1rw
	9576	0xc28cc60000	0xc28cc61000	         4	rw-        	full          	libtracker.so_seg2rw
	9811	0xc372a84000	0xc372a91000	        52	r-x        	full          	libLanguageUtils.so.4.8.0_seg0r
	9812	0xc372c91000	0xc372c92000	         4	rw-        	full          	libLanguageUtils.so.4.8.0_seg1r
	9529	0xc5a3fa3000	0xc5a3fa4000	         4	r-x        	full          	libgthread-2.0.so.0.5701.0_seg0
	9530	0xc5a41a3000	0xc5a41a4000	         4	rw-        	full          	libgthread-2.0.so.0.5701.0_seg1
	9483	0xca66572000	0xca66b6e000	      6128	r-x        	full          	libQt5Widgets.so.5.12.0_seg0ro
	9484	0xca66d6e000	0xca66da0000	       200	rw-        	full          	libQt5Widgets.so.5.12.0_seg1rw
	9831	0xcd67a41000	0xcd67f2d000	      5040	r-x        	full          	libQt5Designer.so.5.12.0_seg0ro
	9832	0xcd6812d000	0xcd68146000	       100	rw-        	full          	libQt5Designer.so.5.12.0_seg1rw
	9480	0xcf42cdf000	0xcf42edb000	      2032	r-x        	full          	libUtils.so.4.8.0_seg0ro
	9481	0xcf430db000	0xcf430ef000	        80	rw-        	full          	libUtils.so.4.8.0_seg1rw
	9482	0xcf430ef000	0xcf430f0000	         4	rw-        	full          	libUtils.so.4.8.0_seg2rw
	10008	0xcfed19d000	0xcfed1a3000	        24	r-x        	full          	libqico.so_seg0ro
	10009	0xcfed3a3000	0xcfed3a4000	         4	rw-        	full          	libqico.so_seg1rw
	9853	0xd019495000	0xd0195bc000	      1180	r-x        	full          	libQmakeProjectManager.so_seg0r
	9854	0xd0197bc000	0xd0197c6000	        40	rw-        	full          	libQmakeProjectManager.so_seg1r
	9807	0xd12ba34000	0xd12bb2e000	      1000	r-x        	full          	libCppEditor.so_seg0ro
	9808	0xd12bd2d000	0xd12bd3c000	        60	rw-        	full          	libCppEditor.so_seg1rw
	9478	0xd24ca4a000	0xd24ca4f000	        20	r-x        	full          	libAggregation.so.4.8.0_seg0ro
	9479	0xd24cc4e000	0xd24cc4f000	         4	rw-        	full          	libAggregation.so.4.8.0_seg1rw
	9493	0xdabbf3f000	0xdabc431000	      5064	r-x        	full          	libQt5Core.so.5.12.0_seg0ro
	9494	0xdabc631000	0xdabc63e000	        52	rw-        	full          	libQt5Core.so.5.12.0_seg1rw
	9495	0xdabc63e000	0xdabc642000	        16	rw-        	full          	libQt5Core.so.5.12.0_seg2rw
	9862	0xdaf96cb000	0xdaf96ea000	       124	r-x        	full          	libPythonEditor.so_seg0ro
	9863	0xdaf98ea000	0xdaf98ec000	         8	rw-        	full          	libPythonEditor.so_seg1rw
	9470	0xdb15885000	0xdb158a7000	       136	r-x        	full          	runtime_loader_seg0ro
	9471	0xdb15aa6000	0xdb15aa8000	         8	rw-        	full          	runtime_loader_seg1rw
	9845	0xe458125000	0xe4581be000	       612	r-x        	full          	libHelp.so_seg0ro
	9846	0xe4583be000	0xe4583c5000	        28	rw-        	full          	libHelp.so_seg1rw
	9876	0xf2a5a3c000	0xf2a5a4d000	        68	r-x        	full          	libWelcome.so_seg0ro
	9877	0xf2a5c4d000	0xf2a5c4e000	         4	rw-        	full          	libWelcome.so_seg1rw
	9539	0xfb36a66000	0xfb36a71000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	9540	0xfb36c71000	0xfb36c72000	         4	rw-        	full          	libiculx.so.57.1_seg1rw
	9525	0x106a3c0d000	0x106a3c82000	       468	r-x        	full          	libpcre2-16.so.0.6.0_seg0ro
	9526	0x106a3e81000	0x106a3e82000	         4	rw-        	full          	libpcre2-16.so.0.6.0_seg1rw
	9586	0x10d3b371000	0x10d3b4d0000	      1404	r-x        	full          	libxml2.so.2.9.7_seg0ro
	9587	0x10d3b6cf000	0x10d3b6db000	        48	rw-        	full          	libxml2.so.2.9.7_seg1rw
	9588	0x10d3b6db000	0x10d3b6dc000	         4	rw-        	full          	libxml2.so.2.9.7_seg2rw
	9510	0x10d6d665000	0x10d6d97a000	      3156	r-x        	full          	libbe.so_seg0ro
	9511	0x10d6db7a000	0x10d6dba8000	       184	rw-        	full          	libbe.so_seg1rw
	10018	0x118f1e9f000	0x118f1ea7000	        32	r-x        	full          	libqtiff.so_seg0ro
	10019	0x118f20a6000	0x118f20a7000	         4	rw-        	full          	libqtiff.so_seg1rw
	9821	0x11a2dbf9000	0x11a2dc35000	       240	r-x        	full          	libCodePaster.so_seg0ro
	9822	0x11a2de34000	0x11a2de37000	        12	rw-        	full          	libCodePaster.so_seg1rw
	9801	0x11ace38c000	0x11ace3cd000	       260	r-x        	full          	libResourceEditor.so_seg0ro
	9802	0x11ace5cd000	0x11ace5d0000	        12	rw-        	full          	libResourceEditor.so_seg1rw
	9474	0x11ff8eb6000	0x11ff8ed1000	       108	r-x        	full          	Qt Creator_seg0ro
	9475	0x11ff90d1000	0x11ff90d2000	         4	rw-        	full          	Qt Creator_seg1rw
	10020	0x12693579000	0x126935e9000	       448	r-x        	full          	libtiff.so.5.4.0_seg0ro
	10021	0x126937e8000	0x126937ec000	        16	rw-        	full          	libtiff.so.5.4.0_seg1rw
	9825	0x13a4cffd000	0x13a4d01f000	       136	r-x        	full          	libBookmarks.so_seg0ro
	9826	0x13a4d21f000	0x13a4d221000	         8	rw-        	full          	libBookmarks.so_seg1rw
	9870	0x14adaca1000	0x14adaca9000	        32	r-x        	full          	libTaskList.so_seg0ro
	9871	0x14adaea8000	0x14adaea9000	         4	rw-        	full          	libTaskList.so_seg1rw
	10041	0x14e1c0fc000	0x14e1c115000	       100	r-x        	full          	libqgenericbearer.so_seg0ro
	10042	0x14e1c314000	0x14e1c315000	         4	rw-        	full          	libqgenericbearer.so_seg1rw
	9833	0x14e5fb48000	0x14e5fc49000	      1028	r-x        	full          	libCMakeProjectManager.so_seg0r
	9834	0x14e5fe49000	0x14e5fe50000	        28	rw-        	full          	libCMakeProjectManager.so_seg1r
	9813	0x1550b220000	0x1550b24f000	       188	r-x        	full          	libQmlDebug.so.4.8.0_seg0ro
	9814	0x1550b44f000	0x1550b451000	         8	rw-        	full          	libQmlDebug.so.4.8.0_seg1rw
	9809	0x156005a3000	0x15600871000	      2872	r-x        	full          	libDebugger.so_seg0ro
	9810	0x15600a70000	0x15600a87000	        92	rw-        	full          	libDebugger.so_seg1rw
	9792	0x157511ea000	0x157515f9000	      4156	r-x        	full          	libProjectExplorer.so_seg0ro
	9793	0x157517f8000	0x1575181d000	       148	rw-        	full          	libProjectExplorer.so_seg1rw
	10010	0x169d6440000	0x169d644a000	        40	r-x        	full          	libqjpeg.so_seg0ro
	10011	0x169d6649000	0x169d664a000	         4	rw-        	full          	libqjpeg.so_seg1rw
	9879	0x16ff70f1000	0x16ff7102000	        68	r-x        	full          	libqsqlite.so_seg0ro
	9880	0x16ff7302000	0x16ff7303000	         4	rw-        	full          	libqsqlite.so_seg1rw
	9874	0x170b8633000	0x170b86d6000	       652	r-x        	full          	libValgrind.so_seg0ro
	9875	0x170b88d5000	0x170b88db000	        24	rw-        	full          	libValgrind.so_seg1rw
	9579	0x171093e1000	0x1710948e000	       692	r-x        	full          	libfreetype.so.6.16.1_seg0ro
	9580	0x1710968e000	0x17109695000	        28	rw-        	full          	libfreetype.so.6.16.1_seg1rw
	9859	0x183b50e4000	0x183b52d3000	      1980	r-x        	full          	libModeling.so.4.8.0_seg0ro
	9860	0x183b54d2000	0x183b54e3000	        68	rw-        	full          	libModeling.so.4.8.0_seg1rw
	9861	0x183b54e3000	0x183b54e4000	         4	rw-        	full          	libModeling.so.4.8.0_seg2rw
	9547	0x1844dda8000	0x1844ddaf000	        28	r-x        	full          	libbsd.so_seg0ro
	9548	0x1844dfaf000	0x1844dfb0000	         4	rw-        	full          	libbsd.so_seg1rw
	9544	0x18456b6c000	0x18456c35000	       804	r-x        	full          	libzstd.so.1.3.7_seg0ro
	9545	0x18456e35000	0x18456e36000	         4	rw-        	full          	libzstd.so.1.3.7_seg1rw
	10004	0x187d8cdb000	0x187d8ce2000	        28	r-x        	full          	libqgif.so_seg0ro
	10005	0x187d8ee1000	0x187d8ee2000	         4	rw-        	full          	libqgif.so_seg1rw
	9779	0x18bdf97d000	0x18bdfc33000	      2776	r-x        	full          	libCore.so_seg0ro
	9780	0x18bdfe32000	0x18bdfe4d000	       108	rw-        	full          	libCore.so_seg1rw
	9533	0x1908b8c8000	0x1908b8d1000	        36	r-x        	full          	libintl.so.8.1.5_seg0ro
	9534	0x1908bad1000	0x1908bad2000	         4	rw-        	full          	libintl.so.8.1.5_seg1rw
	9551	0x192e6daa000	0x192e6ded000	       268	r-x        	full          	libpcre.so.1.2.10_seg0ro
	9552	0x192e6fed000	0x192e6fee000	         4	rw-        	full          	libpcre.so.1.2.10_seg1rw
	9514	0x1944bbf4000	0x1944bc10000	       112	r-x        	full          	libz.so.1.2.11_seg0ro
	9515	0x1944be0f000	0x1944be10000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	9504	0x19e4ec52000	0x19e4edb1000	      1404	r-x        	full          	libroot.so_seg0ro
	9505	0x19e4efb0000	0x19e4efbe000	        56	rw-        	full          	libroot.so_seg1rw
	9506	0x19e4efbe000	0x19e4f003000	       276	rw-        	full          	libroot.so_seg2rw
	9488	0x1a04d276000	0x1a04d27b000	        20	r-x        	full          	libQt5Concurrent.so.5.12.0_seg0
	9489	0x1a04d47b000	0x1a04d47c000	         4	rw-        	full          	libQt5Concurrent.so.5.12.0_seg1
	9584	0x1ac9a998000	0x1ac9a9ad000	        84	r-x        	full          	libtranslation.so_seg0ro
	9585	0x1ac9abac000	0x1ac9abae000	         8	rw-        	full          	libtranslation.so_seg1rw
	9794	0x1b248683000	0x1b24885c000	      1892	r-x        	full          	libQtcSsh.so.4.8.0_seg0ro
	9795	0x1b248a5c000	0x1b248a6c000	        64	rw-        	full          	libQtcSsh.so.4.8.0_seg1rw
	9796	0x1b248a6c000	0x1b248a6d000	         4	rw-        	full          	libQtcSsh.so.4.8.0_seg2rw
	9788	0x1b4e15f5000	0x1b4e1809000	      2128	r-x        	full          	libTextEditor.so_seg0ro
	9789	0x1b4e1a08000	0x1b4e1a18000	        64	rw-        	full          	libTextEditor.so_seg1rw
	9805	0x1bcf225f000	0x1bcf2283000	       144	r-x        	full          	libBinEditor.so_seg0ro
	9806	0x1bcf2483000	0x1bcf2485000	         8	rw-        	full          	libBinEditor.so_seg1rw
	9563	0x1bd0962e000	0x1bd0963f000	        68	r-x        	full          	libroot-addon-icu.so_seg0ro
	9564	0x1bd0983f000	0x1bd09840000	         4	rw-        	full          	libroot-addon-icu.so_seg1rw
	9866	0x1c4371b3000	0x1c437222000	       444	r-x        	full          	libQnx.so_seg0ro
	9867	0x1c437421000	0x1c437426000	        20	rw-        	full          	libQnx.so_seg1rw
	9558	0x1c4bf962000	0x1c4c1ea2000	     38144	rw-        	full          	heap
	9589	0x1d4d7c6c000	0x1d4d7c7b000	        60	r-x        	full          	libbz2.so.1.0.6_seg0ro
	9590	0x1d4d7e7a000	0x1d4d7e7c000	         8	rw-        	full          	libbz2.so.1.0.6_seg1rw
	9527	0x1d5588fa000	0x1d558906000	        48	r-x        	full          	libdouble-conversion.so.1.0.0_s
	9528	0x1d558b05000	0x1d558b06000	         4	rw-        	full          	libdouble-conversion.so.1.0.0_s
	9521	0x1daec52f000	0x1daec6c7000	      1632	r-x        	full          	libicuuc.so.57.1_seg0ro
	9522	0x1daec8c6000	0x1daec8db000	        84	rw-        	full          	libicuuc.so.57.1_seg1rw
	9823	0x1dc6b9a3000	0x1dc6ba0a000	       412	r-x        	full          	libDiffEditor.so_seg0ro
	9824	0x1dc6bc0a000	0x1dc6bc0e000	        16	rw-        	full          	libDiffEditor.so_seg1rw
	9512	0x1dc7f9f3000	0x1dc7fa24000	       196	r-x        	full          	libpng16.so.16.35.0_seg0ro
	9513	0x1dc7fc24000	0x1dc7fc25000	         4	rw-        	full          	libpng16.so.16.35.0_seg1rw
	9537	0x1e63cbd8000	0x1e63cc2d000	       340	r-x        	full          	libicule.so.57.1_seg0ro
	9538	0x1e63ce2d000	0x1e63ce30000	        12	rw-        	full          	libicule.so.57.1_seg1rw
	9490	0x1e8b8bcf000	0x1e8b8d5a000	      1580	r-x        	full          	libQt5Network.so.5.12.0_seg0ro
	9491	0x1e8b8f5a000	0x1e8b8f62000	        32	rw-        	full          	libQt5Network.so.5.12.0_seg1rw
	9492	0x1e8b8f62000	0x1e8b8f63000	         4	rw-        	full          	libQt5Network.so.5.12.0_seg2rw
	10006	0x1eb24cc8000	0x1eb24cd1000	        36	r-x        	full          	libqicns.so_seg0ro
	10007	0x1eb24ed0000	0x1eb24ed1000	         4	rw-        	full          	libqicns.so_seg1rw
	9476	0x1f0172e7000	0x1f017326000	       252	r-x        	full          	libExtensionSystem.so.4.8.0_seg
	9477	0x1f017525000	0x1f017528000	        12	rw-        	full          	libExtensionSystem.so.4.8.0_seg
	9827	0x1f67a328000	0x1f67a375000	       308	r-x        	full          	libDesigner.so_seg0ro
	9828	0x1f67a574000	0x1f67a579000	        20	rw-        	full          	libDesigner.so_seg1rw
	9803	0x1f820b74000	0x1f820c6a000	       984	r-x        	full          	libQtSupport.so_seg0ro
	9804	0x1f820e69000	0x1f820e70000	        28	rw-        	full          	libQtSupport.so_seg1rw
	9581	0x200814c2000	0x2008154c000	       552	r-x        	full          	libQt5DBus.so.5.12.0_seg0ro
	9582	0x2008174c000	0x2008174e000	         8	rw-        	full          	libQt5DBus.so.5.12.0_seg1rw
	9583	0x2008174e000	0x2008174f000	         4	rw-        	full          	libQt5DBus.so.5.12.0_seg2rw
	9535	0x23542a09000	0x23542a15000	        48	r-x        	full          	libicuio.so.57.1_seg0ro
	9536	0x23542c14000	0x23542c16000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	9507	0x252e4896000	0x252e4cbe000	      4256	r-x        	full          	libQt5Qml.so.5.12.0_seg0ro
	9508	0x252e4ebe000	0x252e4edc000	       120	rw-        	full          	libQt5Qml.so.5.12.0_seg1rw
	9509	0x252e4edc000	0x252e4ede000	         8	rw-        	full          	libQt5Qml.so.5.12.0_seg2rw
	10053	0x7f0546274000	0x7f05462b9000	       276	rw-s       	full          	pthread func_809_stack
	10045	0x7f0a121d1000	0x7f0a12216000	       276	rw-s       	full          	pthread func_808_stack
	9601	0x7f254e6ce000	0x7f254e713000	       276	rw-s       	full          	BApplication_thread_806_stack
	9469	0x7f354e0fb000	0x7f354e103000	        32	r-xS       	full          	commpage
	21877	0x7f5ca6791000	0x7f5ca67d6000	       276	rw-s       	full          	w>Qt Creator_905_stack
	23238	0x7fd373201000	0x7fd373246000	       276	rw-s       	full          	w>QtCreator_931_stack
	9468	0x7fd7f9714000	0x7fd7fa715000	     16388	rw-s       	full          	Qt Creator_803_stack
	23268	0x7fe069f43000	0x7fe069f88000	       276	rw-s       	full          	w>QtCreator_945_stack
	9466	0x7fe376d52000	0x7fe376d56000	        16	rw-        	full          	user area
	10040	0x7ff949d8d000	0x7ff949dd2000	       276	rw-s       	full          	pthread func_807_stack

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	5083	    0	        803	some BBlockCache lock
	5084	    0	          0	Catalog
	5085	    0	          0	some BLocker
	5086	    0	          0	some BLocker
	5087	    0	        905	token space
	5088	    0	        905	BLooperList lock
	5089	    0	       1359	AppServerLink_sLock
	5090	    0	          0	LocaleRosterData
	5091	    0	          0	some BLocker
	5192	    0	          0	Catalog
	5195	    0	          0	PeriodicUpdatePoses
	5196	    0	          0	Light Lock
	5197	    0	          0	Light Lock
	5198	    0	          0	undo
	5199	    0	          0	some BLocker
	5200	    0	          0	some BLocker
	5201	    0	          0	BMessageQueue Lock
	5202	    0	          0	AppLooperPort
	5215	    0	          0	screen list
	5217	    0	          0	clipboard
	5218	    0	          0	width buffer
	7073	    0	          0	BMessageQueue Lock
	7074	    0	        905	
	7235	    0	          0	tool tip manager
	7616	    0	          0	BMessageQueue Lock
	7617	    0	        931	
	7626	    0	          0	BMessageQueue Lock
	7627	    0	          0	offscreen bitmap
	7797	    0	          0	BMessageQueue Lock
	7798	    0	        945	
	7808	    0	          0	BMessageQueue Lock
	7809	    0	          0	offscreen bitmap
```
</details>

**Comment by waddlesplash** [comment]
Perhaps the especially interesting part is this:
```
		0x7fd7fa713940	0x1ca3169ec6	g_main_context_iteration + 0x45 
		0x7fd7fa7139a0	0xdabc2068bc	QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 0x5c 
```

Why are we using the Glib event dispatcher?!

**Comment by threedeyes** [comment]
Qt have a QEventDispatcherUNIX (pipes), QEventDispatcherWin32, QEventDispatcherWinRT,  QEventDispatcherCoreFoundation(MacOS) and QEventDispatcherGlib. We can use only QEventDispatcherUNIX  or QEventDispatcherGlib event dispatcher for now. Or we can write new native BeAPI event looper.

**Comment by waddlesplash** [comment]
Well, no matter what event dispatcher is used, it definitely should not crash.

**Comment by diversys** [comment]
> * Try creating a "Generic" (Imported) project; it never opens, even ones that opened in previous versions. Nothing happens.

I don't see "Generic" project option in New project wizard. How do I find it?
![image](https://user-images.githubusercontent.com/1316513/51314548-03d5bd80-1a61-11e9-9f71-7b337812fad3.png)

**Comment by waddlesplash** [comment]
Yes, that's the one, it's not called Generic anymore (though I think the plugin still has this name) but "Import Existing Project."

**Comment by threedeyes** [comment]
I hope this bug fixed in b70ed4259fc96bebb66433da06e7df770b8eb46d
Can you test QtCreator after switch back build with libclang 5.0?

**Comment by kenmays** [comment]
@threedeyes - QT Creator 4.8.1-2 on hrev53067 x86_gcc2
- Importing worked without crash.
- Debug project worked without crash.
- Valgrind analyzing with/without GDB) worked without crash.
- Git usage works with project

Nothing major at the moment. Check with others on their usage.

**Comment by waddlesplash** [comment]
".creator" projects still do not work; they cause something to lock up internally and never appear, even with the new build. @diversys managed to reproduce the problem on his end, so maybe more progress can be made here.

**Comment by diversys** [comment]
I had reproduced it by deleting `/boot/home/config/settings/QtProject` and starting Qt Creator from QuickLaunch. It couldn't find git and importing existing projects didn't work. This is https://dev.haiku-os.org/ticket/12534. To make it work I started Qt Creator from Terminal clicked `Make Default` in Tools->Options->Kits: 

![image](https://user-images.githubusercontent.com/1316513/82890904-9770a580-9f55-11ea-9f75-32c8b8dc8faa.png)

**Comment by waddlesplash** [comment]
Indeed, I can now import existing projects after doing that. Strange; why doesn't Qt Creator report an error instead of doing nothing? Perhaps QProcess is not failing properly?

**Comment by Begasus** [comment]
Is this still valid? Updated locally to QtCreator 14.0.0, and without changes it looks like this.
![qtcreator_default](https://github.com/user-attachments/assets/2a1b848b-f25d-4a33-ab2b-378a141992e5)

**Comment by waddlesplash** [comment]
Yes, if this was due to environs, it's now fixed after the bug in Haiku was.
