### ISSUE TITLE
Arduino is missing in HaikuDepot

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#4002]
Arduino is missing in HaikuDepot. I hear it used to be available. Having an older version would be better than having no version.

**Comment by threedeyes** [comment]
Arduino for Haiku x64 is already available in HaikuDepot.
PS:Today I am fixing build problems for a 32 bit system.

**Comment by probonopd** [comment]
Thank you very much :+1: 

What would need to happen for the recent version to be feasible?

**Comment by probonopd** [comment]
Maybe a dependency is still missing?

```
~/Desktop> uname -a
Haiku shredder 1 hrev53259+3 Jul 15 2019 23:37:0 x86_64 x86_64 Haiku
~/Desktop> /system/apps/Arduino/Arduino\ IDE 
Signature in rsrc doesn't match constructor arg. (application/x-vnd.ArduinoIDE, application/x-vnd.arduino)
~/Desktop> runtime_loader: Cannot open file libjli.so: No such file or directory
```

**Comment by threedeyes** [comment]
hm. openjdk8_jre installed?

**Comment by threedeyes** [comment]
>What would need to happen for the recent version to be feasible?
For new version we need port latest golang (for arduino_builder utilty).

**Comment by probonopd** [comment]
> hm. openjdk8_jre installed?

No, it was not installed on my system. If it is needed, shouldn't it have been installed when I installed the Arduino package?

**Comment by probonopd** [comment]
Manually installing openjdk8_jre makes no difference for me.

**Comment by threedeyes** [comment]
Ok. I try install it on clean system tonight and test.

**Comment by threedeyes** [comment]
Fixed. Try now, please.

**Comment by probonopd** [comment]
Thanks @threedeyes, I had 1.7.11-3 already on my system and no update was offered. Uninstalling and reinstalling it resulted it in being re-downloaded, but the error persists. Are you sure it was uploaded to HaikuDepot or am I supposed to download it somewhere else?

**Comment by threedeyes** [comment]
The problem is solved in 1.7.11-4 - which has just been builded - https://build.haiku-os.org/buildmaster/master/x86_64/

Apparently not yet published in the repository foe now.

**Comment by threedeyes** [comment]
Try now again, please. 1.7.11-4 version available in HaikuDepot for now.

**Comment by probonopd** [comment]
Thank you @threedeyes it is working for me now. :+1:

**Comment by threedeyes** [comment]
Fixed in 18d50660704d2407b8a28657459fe42507dfc48a
