### ISSUE TITLE
Trouble updating LibreOffice packages (libuuid_x86>=1.3.1)

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#4981]
Hello. I'm having this issue doing a "pkgman update" or "pkgman full-sync" in Haiku 32 bits:

Encountered problems:
problem 1: package libreoffice_x86-6.4.3.1-5 requires lib:libuuid_x86>=1.3.1, but none of the providers can be installed
  solution 1:
    - keep libreoffice_x86-6.4.3.1-4 from excluded repository
  solution 2:
    - allow deinstallation of util_linux_x86-2.34-1
    - allow deinstallation of util_linux_x86_devel-2.34-1
Please select a solution, skip the problem for now or quit.
select [1...2/s/q]:

**Comment by korli** [comment]
@kallisti5 which should be used for libreoffice util_linux or libuuid?

**Comment by kallisti5** [comment]
Good question.

There were some issues in libuuid in util_linux per #4266

I fixed these issues via:

https://github.com/haikuports/haikuports/commit/ce55d8052b51c8e953a5a35b2b4f87cfd3592e12#diff-00c37ba425f5eda86c7e90ceefa67de9

*HOWEVER* scons was broken per #4726 which means my updated libuuid package was broken from building.

@korli  It looks like you corrected the libuuid recipe though (assuming scons was fixed?)
https://github.com/haikuports/haikuports/commit/d033783342a95c422294a24a3bfc0adffb2540f8

So, i'd use my libuuid fork. libuuid doesn't change much.

**Comment by korli** [comment]
Should be fixed with 615cb00eabc18653eb0447de599e8d74938a09f6

**Comment by unspacyar** [comment]
Hello. I see the new version of libuuid (1.3.1-4) appears at the Depot. However, I still get the issue when trying to update / full-sync.  

What is the recommended procedure? Unninstal LibreOffice package and trying to install it again?  Thanks in advance!

**Comment by korli** [comment]
pkgman will propose to uninstall util_linux because it conflicts with libuuid. select this option.

**Comment by unspacyar** [comment]
Thank you @korli !!!
