### ISSUE TITLE
paladin: build issue with 2.7-1 x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5198]
Tested on hrev54418 x86_gcc2 (GCC2). 
NOTE: Passed on second build attempt.
```
Linking
Updating resources
Success
Paladin: ../haiku-git/src/system/libroot/posix/malloc_hoard2/superblock.h:194:void BPrivate::superblock::putBlock(BPrivate::block *): getNumAvailable() < getNumBlocks()
./buildsuite.sh: line 32:  1444 Kill Thread             $START_DIRECTORY/Paladin/Paladin -b "$TMPPROJ"
Failed to build SymbolFinder.nodebug.pld. Error code 149
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2
Error: Build has failed - stopping.
```

**Comment by kenmays** [comment]
Resolved here: https://github.com/adamfowleruk/Paladin/issues/365

**Comment by Begasus** [comment]
Still not checked, but if so, then a version bump should be needed at paladin (should be checked first)

**Comment by kenmays** [comment]
Fixed in 2.8~git recipe.
