### ISSUE TITLE
LibreOffice 7.0 crashes on file open

### ISSUE THREAD

**Issue by bitigchi** [haikuports/haikuports#5251]
Steps:

- Save a new file 
- Try to reopen the file

LibreOffice crashes.

```
Debug information for team /boot/system/apps/LibreOffice/program/LibreOffice (2945):
CPU(s): 4x Intel Core™ i5-4460 
Memory: 7.95 GiB total, 682.27 MiB used
Haiku revision: hrev54503 Aug 14 2020 06:02:31 (x86_64)

Active Threads:
	thread 2948: BApplication_thread 
	thread 2950: pthread func 
	thread 2963: w>LibreOffice 
	thread 2998: team 2945 debug task 
	thread 2945: LibreOffice (main)
		state: Exception (General protection fault)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7ffca93a1b30	0x1214d720243	HMAC_Destroy + 0x23 
			Disassembly:
				HMAC_Destroy:
				0x000001214d720220:           4885ff  test %rdi, %rdi
				0x000001214d720223:             746b  jz 0x4d720290
				0x000001214d720225:               55  push %rbp
				0x000001214d720226:           4889e5  mov %rsp, %rbp
				0x000001214d720229:             4154  push %r12
				0x000001214d72022b:           4189f4  mov %esi, %r12d
				0x000001214d72022e:               53  push %rbx
				0x000001214d72022f:           4889fb  mov %rdi, %rbx
				0x000001214d720232:           488b3f  mov (%rdi), %rdi
				0x000001214d720235:           4885ff  test %rdi, %rdi
				0x000001214d720238:             743a  jz 0x4d720274
				0x000001214d72023a:         488b4308  mov 0x8(%rbx), %rax
				0x000001214d72023e:       be01000000  mov $0x1, %esi
				0x000001214d720243:           ff5018  call 0x18(%rax) <--
```

**Comment by CodeforEvolution** [comment]
For the moment, we should really revert to an older, working version of LibreOffice. This was reported four day ago after all...

**Comment by kenmays** [comment]
@bitigchi @CodeforEvolution - Verified LibreOffice 7.0 issue. Libreoffice-6.4.3.1-8 works properly for this task and is available.

**Comment by kenmays** [comment]
@bitigchi - Issue fixed in LibreOffice 7.0.1.2-2 package.

**Comment by humdingerb** [comment]
Still crashing here. I only get a debug report when opening a new Writer document and open a file from there:
https://oshi.at/oeGNxT/LibreOffice-2118-debug-01-09-2020-15-33-02.report

When trying to open from the 'Launcher', I just get a window telling me LibreOffice has crashed.

**Comment by diversys** [comment]
> Still crashing here. I only get a debug report when opening a new Writer document and open a file from there:
> https://oshi.at/oeGNxT/LibreOffice-2118-debug-01-09-2020-15-33-02.report
> 
> When trying to open from the 'Launcher', I just get a window telling me LibreOffice has crashed.

According to the backtrace this crash is unrelated.

**Comment by waddlesplash** [comment]
Is this still a problem?
