### ISSUE TITLE
OpenBLAS build fails on 64 bit

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#5953]
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/5744/builds/19109.log

Locally it builds fine outside of HP, but not with HP. I can't seem to find the reason.

**Comment by korli** [comment]
is it on beta2?

**Comment by extrowerk** [comment]
no, on nightly.

**Comment by Begasus** [comment]
Doing a local build with haikuporter atm (this will take some time), on R1B2 (32bit) it builds ok, now checking a build for 64bit on a nightly

**Comment by korli** [comment]
you could try with 'hp -E', then 'strace ./openblas_utest'

**Comment by Begasus** [comment]
Seems to be running "out of memory"? 

```
[   579] resize_area(0x23b5, 0x88c0000) = 0x80000000 Out of memory (1002599 us)
[   579] --- Segmentation violation (Segmentation violation) ---
```

https://paste.ubuntu.com/p/VSBQwVYZnd/

**Comment by wattoc** [comment]
Is it still necessary to disable AVX on these builds?  I was under the impression AVX was now possible on Haiku?

**Comment by pulkomandy** [comment]
AVX is possible but we still support machines without AVX support. So please enable it only if it can detect at runtime if it's available on the CPU and use it only in that case (not familiar with openblas, I don't know if it can do that)

**Comment by wattoc** [comment]
It's meant to detect the CPU at runtime I believe - that's the purpose of the DYNAMIC_ARCH build option.  I would still defer to someone who knows it better, hence the question :)

**Comment by korli** [comment]
Build fails also with 0.3.17 on the x86_64 buildbot:
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/5876/builds/75596.log

**Comment by wattoc** [comment]
Fails to build on my main PC also.  I've also had 0.3.15 build just fine on the same PC.  The whole thing doesn't inspire much confidence, there's a lot of variation of it working or not between fairly similar hardware.

Do you know what CPU the buildbot presents as?

**Comment by korli** [comment]
I kept only the libs and shared build, so that tests are not executed.  Should be fixed with cd829356a30ddc4ec41661d3fb385f9d85b6912f

**Comment by wattoc** [comment]
Re: 0.3.17 It will still crash on load if you try to use the library - it's crashing due to memory allocation on startup.  It looks like it's trying to allocate some sort of buffer memory to the threads it is defined with - after a few of them it just blows up.

You can fix it (at least here) by artificially reducing the number of threads to say 4 eg. NUM_THREADS=4

That's not really a solution long term, since it limits the total number of threads that can ever be used with openblas.  It may also just be making the problem less likely to happen - eg. if someone creates a big enough set it may still crash.

I have no idea why it works/not works otherwise on some versions or some combinations of CPU rather than others.

I've seen there were some changes to buffer size between 3.9 and 3.10, but tweaking that here hasn't made any difference.

**Comment by Begasus** [comment]
> NUM_THREADS=4

Just a quick look at repology I found that Alpine uses something simular?

https://git.alpinelinux.org/aports/tree/community/openblas/APKBUILD#n36

**Comment by wattoc** [comment]
Looks like they use 8 for x86?  PPC uses 64 and others 32.  I've seen it recommended to use 128.  Interesting that they've disabled OPEN_MP in their build, haven't tried doing that.

As I understand it, the NUM_THREADS is basically setting an upper limit to how many threads openblas can ever use - may be relevant to anyone wanting to use Haiku for scientific computing.  In practice it can and probably will use much less than that unless you're doing some massive specialist research task which I'm not sure Haiku is currently a major target for.  I get the impression that since it's set at compile time, on launch it goes off and allocates some storage space for NUM_THREADS threads even if they are not used.  If you have a Threadripper or something, the more threads you can have concurrently the better.

The thing that bothers me is it seems more like avoiding an issue vs fixing it.  It may manifest in problems down the line when people are using the package and it starts segfaulting because they're messing with some huge matrices - could be irrespective of how many threads are allowed.

If it's just for some apps like digiKam or whatever it may be OK and we may get away with it.

**Comment by pulkomandy** [comment]
It may be a good idea to contact upstream OpenBLAS developers and ask their opinion about it?

**Comment by wattoc** [comment]
I'm trying to get a better understanding of what's going on, if it looks like it's simply malloc calls failing then I'm not sure they will do much other than point back at us.

**Comment by wattoc** [comment]
So the crashing issue looks like a RAM issue and not an actual "bug" as such.

What the problem is as far as I can tell though is that there's some checks that should be performed which should detect the number of CPUs or processor threads available on the local machine and then alloc based on that.

I think what's happening in our case is those checks aren't coming back with anything valid, and so the default is to allocate the NUM_THREADS, which in our case is set to 64.  I bumped up the RAM in VirtualBox and the problem went away.

This may explain why some were experiencing this issue vs. others.

I'm pretty sure if it's crashing for you, you can set the OMP_NUM_THREADS to a sane number (eg. the number of hardware threads for your CPU) and it should start working.

I did try to sort some stuff which should make it max out to the number of threads on your CPU, but it didn't seem to work.  Currently the code is actually missing OS_HAIKU in the defines for that check, but it also appears as if the call isn't working anyway.

Please bear with me for a bit, I'll try to get a patch sorted if I can.

**Comment by wattoc** [comment]
On the OS_HAIKU defines missing, I'd somehow inadvertently cleaned the build folder, so had to reapply my change.  I'll update but I think it should work.

**Comment by wattoc** [comment]
Changes do appear to work, doing some further testing/juggling packaging and will have a pull req in soon hopefully
