### ISSUE TITLE
lagrange freezes if window is resized

### ISSUE THREAD

**Issue by iam-git** [haikuports/haikuports#6068]
Contrary to #5850, 1.5.2 version forks fine for me on x64, but only if not to resize window. There is some chance for lagrange not to crash if runned with --sw, but software rendering is ugly itself.

**Comment by sikmir** [comment]
The problem with resizing main window still exists (Lagrange 1.6.1).

**Comment by skyjake** [comment]
Is there a stack trace of the crash available?

**Comment by skyjake** [comment]
Could you elaborate a bit on what the issue is here?

You resize the window and the app freezes? Is it completely unresponsive, or can you for example still quit it with Ctrl+Q (suggesting it's the redrawing that's stopped and not the app event loop).

**Comment by sikmir** [comment]
> You resize the window and the app freezes? Is it completely unresponsive, or can you for example still quit it with Ctrl+Q (suggesting it's the redrawing that's stopped and not the app event loop).

Yes, exactly, there is no way to quit after the app freezes.

**Comment by skyjake** [comment]
If you run the app under a debugger, could you get a stack trace of where it is hanging?

**Comment by korli** [comment]
> If you run the app under a debugger, could you get a stack trace of where it is hanging?

Or in the kernel debugger.

**Comment by Begasus** [comment]
@iam-git could you confirm this is fixed?

**Comment by iam-git** [comment]
// Finally, I've updated Haiku and all packages to the latest versions (on one of my machines)
I see it is reopened... Indeed, resizing still freezes Lagrange, but at least maximization ("zoom") widget works reliably now.

**Comment by sikmir** [comment]
With update to 1.10.1 resizing crashes lagrange instead of freezing:
```
		Frame		IP			Function Name
		-----------------------------------------------
		00000000	0x7e373e2627	_kern_debugger + 0x7 
			Disassembly:
				_kern_debugger:
				0x0000007e373e2620:   48c7c0e4000000  mov $0xe4, %rax
				0x0000007e373e2627:             0f05  syscall  <--

		0x7f500ebded20	0x1cd59f8860a	BGLView::EnableDirectMode(bool) + 0x3ea (../src/hgl/GLView.cpp:-1)
		0x7f500ebded40	0x10fccf3dfaa	HAIKU_GL_MakeCurrent + 0x4a 
		0x7f500ebded80	0x10fccf11688	SDL_GL_MakeCurrent_REAL + 0x98 
		0x7f500ebdeda0	0x10fcce97ad6	GL_ActivateRenderer + 0x26 
		0x7f500ebdee30	0x10fcce99b56	GL_RunCommandQueue + 0x26 
		0x7f500ebdee50	0x10fcce8f796	SDL_SetRenderTarget_REAL + 0x96 
		0x7f500ebdeeb0	0x10fcce91e4a	SDL_RendererEventWatch + 0x52a 
		0x7f500ebdeee0	0x10fcce7c4b8	SDL_PushEvent_REAL + 0xa8 
		0x7f500ebdef50	0x10fcce8382e	SDL_SendWindowEvent + 0x2ce 
		0x7f500ebdef70	0x10fccf103a5	SDL_OnWindowResized + 0x45 
		0x7f500ebdefe0	0x10fcce835cb	SDL_SendWindowEvent + 0x6b 
		0x7f500ebdf050	0x10fccf41f97	SDL_BApp::MessageReceived(BMessage*) + 0xe7 
		0x7f500ebdf0a0	0x3c9d27ebfe	BLooper::task_looper() + 0x27e 
		0x7f500ebdf0c0	0x3c9d273b5c	BApplication::Run() + 0x1c 
		0x7f500ebdf700	0x10fccf41c15	StartBeApp + 0x85 
		0x7f500ebdf730	0x10fccec44d6	SDL_RunThread + 0x36 
		0x7f500ebdf740	0x10fccf425f4	RunThread + 0x4 
		0x7f500ebdf760	0x7e373f2365	pthread_thread_entry(void*, void*) + 0x15 
		00000000	0x7fffe7436260	commpage_thread_exit + 0 
```

**Comment by diversys** [comment]
cc @X547

**Comment by sikmir** [comment]
Looks like 1.15.7 doesn't have this problem, https://github.com/haikuports/haikuports/pull/8219. Please check.

**Comment by skyjake** [comment]
Based on the backtrace, I would recommend setting Lagrange's CMake option `ENABLE_RESIZE_DRAW` to `OFF`. Looks like the low-level OpenGL code is not cool with redrawing the window during the resizing callback.
