### ISSUE TITLE
pyqt5: version bump issues

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#9808]
The latest [pyqt5 bump](https://github.com/haikuports/haikuports/commit/95d7243c21db6416e7d111d2217c758b5cc1ae45) seems to have triggered [some issues](https://discuss.haiku-os.org/t/latest-system-update-problems/14288).

From https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/report.txt:

```
calibre-5.32.0-6-x86_64.hpkg:
	requires "pyqt5_python39 >= 5.15.9" of package "calibre-5.32.0-6" could not be resolved

fs_uae_launcher-3.0.5-5-x86_64.hpkg:
	requires "pyqt5_python39" of package "fs_uae_launcher-3.0.5-5" could not be resolved

pyqtwebengine5_python39-5.15.6-1-x86_64.hpkg:
	requires "pyqt5_python39 >= 5.15.9" of package "pyqtwebengine5_python39-5.15.6-1" could not be resolved

jdreplace-2.2-2-any.hpkg:
	requires "pyqt5_python39" of package "jdreplace-2.2-2" could not be resolved

git_cola-3.12.0-5-x86_64.hpkg:
	requires "pyqt5_python39 >= 5.15.6" of package "git_cola-3.12.0-5" could not be resolved

openshot-3.1.0-1-any.hpkg:
	requires "pyqt5_python39 >= 5.15.6" of package "openshot-3.1.0-1" could not be resolved

python_poppler_qt5_python39-21.3.0-2-x86_64.hpkg:
	requires "pyqt5_python39 >= 5.15.6" of package "python_poppler_qt5_python39-21.3.0-2" could not be resolved

qutebrowser-2.5.4-1-x86_64.hpkg:
	requires "pyqt5_python39 >= 5.15.6" of package "qutebrowser-2.5.4-1" could not be resolved

picard-2.10-1-x86_64.hpkg:
	requires "pyqt5_python39 >= 5.15.9" of package "picard-2.10-1" could not be resolved

frescobaldi-3.3.0-1-any.hpkg:
	requires "pyqt5_python39 >= 5.15.6" of package "frescobaldi-3.3.0-1" could not be resolved

qscintilla_python39-2.11.6-6-x86_64.hpkg:
	requires "pyqt5_python39 >= 5.15.9" of package "qscintilla_python39-2.11.6-6" could not be resolved

retext-7.0.1-6-x86_64.hpkg:
	requires "pyqt5_python39 >= 5.15.6" of package "retext-7.0.1-6" could not be resolved

qpageview_python39-0.6.2-2-any.hpkg:
	requires "pyqt5_python39 >= 5.15.6" of package "qpageview_python39-0.6.2-2" could not be resolved

jdtextedit-9.1-3-any.hpkg:
	requires "pyqt5_python39" of package "jdtextedit-9.1-3" could not be resolved
```

**Comment by korli** [comment]
Yeah switching to python 3.10 makes the old packages orphaned.

**Comment by Begasus** [comment]
Building pyqt5 ends up in a policy error here (R1B4 64bit), although this won't fail at the buildmaster, maybe should be fixed?
`Warning: POLICY ERROR: Invalid top-level package entry "packages"`

It seems that the api isn't included in the package this way (the case too for the python39 package)?
![pyqt5](https://github.com/haikuports/haikuports/assets/16057090/85013aca-bd66-4ff8-87f1-3fd652758221)

**Comment by Begasus** [comment]
Quick fix I did here was:
```
	mkdir -p $dataDir
	mv $prefix/packages/pyqt5-5.15.10-2/.self/data/sip $dataDir
	rm -r $prefix/packages
```
If that's OK I can push this.

**Comment by ArDrakho** [comment]
This update is from the forum: https://discuss.haiku-os.org/t/latest-system-update-problems/14288/15.

1. Calibre, OpenShot, and Picard are operational now.
2. Web is still broken…
    
[Web-989-debug-03-12-2023-07-03-56.report.txt](https://github.com/haikuports/haikuports/files/13538327/Web-989-debug-03-12-2023-07-03-56.report.txt)
![Web_startup_error_20231203](https://github.com/haikuports/haikuports/assets/48101100/5e8a4dcf-ea1d-4751-aa9a-97130bdafdaa)

4.I attempted to use Ark and that application does not recognize any compression methods whle attempting to open file: ZIP, 7Z, GZIP, TGZ,…I did not check any others. I did not check to see if I can create one.

![Ark_error_20231203](https://github.com/haikuports/haikuports/assets/48101100/38b9b715-040d-4a68-b29c-6f698362a859)
